// ============================================================================
// blink_engine_module_rom.c
// Generated S-expression module for blink_engine (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "blink_engine.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern s_expr_result_t toggle_led(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

// Tree: blink_engine (params=3, nodes=1)
static const s_expr_param_t blink_engine_blink_engine_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t blink_engine_trees[] = {
    {
        .name_hash = 0xD2552918U,
        .record_hash = 0U,
        .params = blink_engine_blink_engine_params,
        .param_count = 3,
        .func_node_count = 1,
        .pointer_count = 0,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t blink_engine_oneshot_fns[1] = { NULL };

static const s_expr_main_fn_t blink_engine_main_fns[] = {
    toggle_led  // 0: toggle_led
};

static const s_expr_pred_fn_t blink_engine_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t blink_engine_module_rom = {
    .name_hash = 0xD2552918U,
    .is_64bit = false,
    .trees = blink_engine_trees,
    .tree_count = 1,
    .records = NULL,
    .record_count = 0,
    .string_table = NULL,
    .string_count = 0,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = blink_engine_oneshot_fns,
    .oneshot_count = 0,
    .main_fns = blink_engine_main_fns,
    .main_count = 1,
    .pred_fns = blink_engine_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 1,
    .max_pointer_count = 0,
    .max_param_count = 3,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

