// ============================================================================
// blink_engine.h
// Generated S-expression module for blink_engine
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef BLINK_ENGINE_H
#define BLINK_ENGINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"

// Module: blink_engine
#define BLINK_ENGINE_NAME_HASH 0xD2552918
#define BLINK_ENGINE_TREE_COUNT 1
#define BLINK_ENGINE_RECORD_COUNT 0

// Function hashes
#define TOGGLE_LED_HASH 0xD47C91E7

// Tree hashes
#define BLINK_ENGINE_HASH 0xD2552918

#ifdef __cplusplus
}
#endif

#endif // BLINK_ENGINE_H
