// ============================================================================
// loop_test_debug.h
// Debug hash reference for loop_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef LOOP_TEST_DEBUG_H
#define LOOP_TEST_DEBUG_H

// Oneshot functions
#define H_FFF84A15 0xFFF84A15  // SE_SET_FIELD
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_2442CEA2 0x2442CEA2  // SE_LOG_INT
#define H_09391555 0x09391555  // SE_INC_FIELD

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_E404E1CF 0xE404E1CF  // SE_FORK_JOIN
#define H_A08B6DD3 0xA08B6DD3  // SE_WHILE
#define H_FFC1FAA4 0xFFC1FAA4  // SE_CHAIN_FLOW
#define H_0C3460EB 0x0C3460EB  // SE_TICK_DELAY
#define H_6B7AA500 0x6B7AA500  // SE_RETURN_PIPELINE_DISABLE
#define H_DFE64C74 0xDFE64C74  // SE_RETURN_TERMINATE

// Predicate functions
#define H_42A88A80 0x42A88A80  // SE_STATE_INCREMENT_AND_TEST
#define H_275252DB 0x275252DB  // SE_FIELD_INCREMENT_AND_TEST

#endif // LOOP_TEST_DEBUG_H
