// ============================================================================
// loop_test_user_functions.h
// User function prototypes for loop_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef LOOP_TEST_USER_FUNCTIONS_H
#define LOOP_TEST_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif // LOOP_TEST_USER_FUNCTIONS_H
