// ============================================================================
// loop_test_module_rom.c
// Generated S-expression module for loop_test (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "loop_test_records.h"
#include "loop_test.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.

static const s_expr_field_desc_t loop_test_loop_test_blackboard_fields[] = {
    { .name_hash = 0x24954557U, .offset = 0, .size = 4 },
    { .name_hash = 0xD0B76C4EU, .offset = 4, .size = 4 },
    { .name_hash = 0x6542B7E7U, .offset = 8, .size = 4 },
    { .name_hash = 0x696CDE6AU, .offset = 12, .size = 4 },
    { .name_hash = 0x1CAA35D8U, .offset = 16, .size = 4 }
};

static const s_expr_record_desc_t loop_test_records[] = {
    { .name_hash = 0x033C03ACU, .total_size = 20, .field_count = 5, .fields = loop_test_loop_test_blackboard_fields }
};

// Tree: loop_test (params=167, nodes=42)
static const s_expr_param_t loop_test_loop_test_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 166, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 69, .parent_offset = 11 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 66, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 4, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 5, .func_index = 0 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 10U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 6 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 6, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 55, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 7, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 2 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 25 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 10, .func_index = 3 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 27, .parent_offset = 15 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 11, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 12, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 23 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 2 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 25 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 3 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 15, .func_index = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 4, .str_len = 21 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 22 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 23 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 17, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 25 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 27, .parent_offset = 42 },
    { .type = 0x07, .index_to_pointer = 1, .brace_idx = 3, .parent_offset = 43 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 18, .func_index = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 46 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 47 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 5, .str_len = 20 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 50 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 51 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 20, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 53 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 55, .parent_offset = 56 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 64 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 66, .parent_offset = 67 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 69, .parent_offset = 80 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 80, .parent_offset = 81 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 21, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 22, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 12, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 23, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 16, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 10U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 67, .parent_offset = 11 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 24, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 1 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 25, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 12, .field_size = 4 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 16, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 6 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 7 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 26, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 55, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 27, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 28, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 29, .func_index = 2 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 25 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 30, .func_index = 3 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 27, .parent_offset = 15 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 31, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 32, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 23 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 33, .func_index = 2 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 25 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 34, .func_index = 3 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x07, .index_to_pointer = 2, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x89, .index_to_pointer = 2, .node_index = 35, .func_index = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 36, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 4, .str_len = 21 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 22 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 23 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 37, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 25 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 27, .parent_offset = 42 },
    { .type = 0x07, .index_to_pointer = 3, .brace_idx = 3, .parent_offset = 43 },
    { .type = 0x89, .index_to_pointer = 3, .node_index = 38, .func_index = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 46 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 47 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 39, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 5, .str_len = 20 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 50 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 51 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 40, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 53 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 55, .parent_offset = 56 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 58, .parent_offset = 65 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 67, .parent_offset = 78 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 80, .parent_offset = 161 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 162 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 41, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 164 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 166, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t loop_test_trees[] = {
    {
        .name_hash = 0xD1A777D8U,
        .record_hash = 0x033C03ACU,
        .params = loop_test_loop_test_params,
        .param_count = 167,
        .func_node_count = 42,
        .pointer_count = 4,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t loop_test_oneshot_fns[] = {
    se_set_field,  // 0: SE_SET_FIELD
    se_log,  // 1: SE_LOG
    se_log_int,  // 2: SE_LOG_INT
    se_inc_field  // 3: SE_INC_FIELD
};

static const s_expr_main_fn_t loop_test_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    se_fork_join,  // 1: SE_FORK_JOIN
    se_while,  // 2: SE_WHILE
    se_chain_flow,  // 3: SE_CHAIN_FLOW
    se_tick_delay,  // 4: SE_TICK_DELAY
    se_return_pipeline_disable,  // 5: SE_RETURN_PIPELINE_DISABLE
    se_return_terminate  // 6: SE_RETURN_TERMINATE
};

static const s_expr_pred_fn_t loop_test_pred_fns[] = {
    se_state_increment_and_test,  // 0: SE_STATE_INCREMENT_AND_TEST
    se_field_increment_and_test  // 1: SE_FIELD_INCREMENT_AND_TEST
};

// Top-level ROM handle (M-port)
const s_engine_rom_t loop_test_module_rom = {
    .name_hash = 0xD1A777D8U,
    .is_64bit = false,
    .trees = loop_test_trees,
    .tree_count = 1,
    .records = loop_test_records,
    .record_count = 1,
    .string_table = loop_test_strings,
    .string_count = 6,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = loop_test_oneshot_fns,
    .oneshot_count = 4,
    .main_fns = loop_test_main_fns,
    .main_count = 7,
    .pred_fns = loop_test_pred_fns,
    .pred_count = 2,
    .max_func_node_count = 42,
    .max_pointer_count = 4,
    .max_param_count = 167,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

