// ============================================================================
// loop_test_records.h
// Generated record structures for loop_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef LOOP_TEST_RECORDS_H
#define LOOP_TEST_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct loop_test_blackboard_s loop_test_blackboard_t;

// Record: loop_test_blackboard (size=20, align=4)
struct loop_test_blackboard_s {
    uint32_t outer_sequence_counter;  // offset=0, size=4
    uint32_t inner_sequence_counter;  // offset=4, size=4
    uint32_t field_test_counter;  // offset=8, size=4
    uint32_t field_test_increment;  // offset=12, size=4
    uint32_t field_test_limit;  // offset=16, size=4
};

#endif // LOOP_TEST_RECORDS_H
