// ============================================================================
// loop_test_dump_32.h
// DEBUG PARAMETER DUMP for loop_test
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef LOOP_TEST_DUMP_32_H
#define LOOP_TEST_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: loop_test
 * Hash:   0xD1A777D8
 * Trees:  1
 * Records: 1
 * Strings: 6
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x6E93DAD2 "loop_sequence_fn start"
 * [0x0001] (  1) hash=0x387A4BDC "outer_sequence_counter %d"
 * [0x0002] (  2) hash=0x5B801D36 "inner_sequence_fn start"
 * [0x0003] (  3) hash=0xCF1F55FB "inner_sequence_counter %d"
 * [0x0004] (  4) hash=0x3FB7E4D3 "inner_sequence_fn end"
 * [0x0005] (  5) hash=0xA15F2357 "loop_sequence_fn end"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0001] ( 1) hash=0xCEBBEFA4 SE_LOG
 *   [0x0002] ( 2) hash=0x2442CEA2 SE_LOG_INT
 *   [0x0003] ( 3) hash=0x09391555 SE_INC_FIELD
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0xE404E1CF SE_FORK_JOIN
 *   [0x0002] ( 2) hash=0xA08B6DD3 SE_WHILE
 *   [0x0003] ( 3) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0004] ( 4) hash=0x0C3460EB SE_TICK_DELAY
 *   [0x0005] ( 5) hash=0x6B7AA500 SE_RETURN_PIPELINE_DISABLE
 *   [0x0006] ( 6) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *
 * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):
 *   [0x0000] ( 0) hash=0x42A88A80 SE_STATE_INCREMENT_AND_TEST
 *   [0x0001] ( 1) hash=0x275252DB SE_FIELD_INCREMENT_AND_TEST
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: loop_test_blackboard (size=20, align=4, hash=0x033C03AC)
 *   [ 0] off=0x0000 size= 4 hash=0x24954557 outer_sequence_counter
 *   [ 1] off=0x0004 size= 4 hash=0xD0B76C4E inner_sequence_counter
 *   [ 2] off=0x0008 size= 4 hash=0x6542B7E7 field_test_counter
 *   [ 3] off=0x000C size= 4 hash=0x696CDE6A field_test_increment
 *   [ 4] off=0x0010 size= 4 hash=0x1CAA35D8 field_test_limit
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: loop_test
 *   hash=0xD1A777D8 nodes=42 ptrs=4
 *   record=loop_test_blackboard (hash=0x033C03AC)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    166      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *    3    ONESHOT   [0x08]      2      0  idx_to_ptr=0
 *    4      FIELD[0x0B]          0      4  outer_sequence_counter (off=0x0000, hash=0x24954557)
 *    5      UINT[0x01]           -      -  0 (0x00000000)
 *    6    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *    7    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *    8    ONESHOT   [0x08]      7      0  idx_to_ptr=0
 *    9      FIELD[0x0B]          4      4  inner_sequence_counter (off=0x0004, hash=0xD0B76C4E)
 *   10      UINT[0x01]           -      -  0 (0x00000000)
 *   11    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   12    OPEN_CALL[0x07]     69      0  SE_FORK_JOIN hash=0xE404E1CF
 *   13    MAIN      [0x09]     12      1  idx_to_ptr=0
 *   14      OPEN_CALL[0x07]     66      0  SE_WHILE hash=0xA08B6DD3
 *   15      MAIN      [0x09]     14      2  idx_to_ptr=0
 *   16        OPEN_CALL[0x07]      4      0  SE_STATE_INCREMENT_AND_TEST hash=0x42A88A80
 *   17        PRED      [0x0A]     16      0  idx_to_ptr=0
 *   18          UINT[0x01]           -      -  1 (0x00000001)
 *   19          UINT[0x01]           -      -  10 (0x0000000A)
 *   20        CLOSE[0x06]          0      -  (end SE_STATE_INCREMENT_AND_TEST)
 *   21        OPEN_CALL[0x07]     58      0  SE_FORK_JOIN hash=0xE404E1CF
 *   22        MAIN      [0x09]     21      1  idx_to_ptr=0
 *   23          OPEN_CALL[0x07]     55      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   24          MAIN      [0x09]     23      3  idx_to_ptr=0
 *   25            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   26            ONESHOT   [0x08]     25      1  idx_to_ptr=0
 *   27              STR_IDX[0x0D]        0     22  "loop_sequence_fn start"
 *   28            CLOSE[0x06]          0      -  (end SE_LOG)
 *   29            OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *   30            ONESHOT   [0x08]     29      2  idx_to_ptr=0
 *   31              STR_IDX[0x0D]        1     25  "outer_sequence_counter %d"
 *   32              FIELD[0x0B]          0      4  outer_sequence_counter (off=0x0000, hash=0x24954557)
 *   33            CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *   34            OPEN_CALL[0x07]      4      0  SE_INC_FIELD hash=0x09391555
 *   35            ONESHOT   [0x08]     34      3  idx_to_ptr=0
 *   36              FIELD[0x0B]          0      4  outer_sequence_counter (off=0x0000, hash=0x24954557)
 *   37              UINT[0x01]           -      -  1 (0x00000001)
 *   38            CLOSE[0x06]          0      -  (end SE_INC_FIELD)
 *   39            OPEN_CALL[0x07]     27      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   40            MAIN      [0x09]     39      3  idx_to_ptr=0
 *   41              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   42              ONESHOT   [0x08]     41      1  idx_to_ptr=0
 *   43                STR_IDX[0x0D]        2     23  "inner_sequence_fn start"
 *   44              CLOSE[0x06]          0      -  (end SE_LOG)
 *   45              OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *   46              ONESHOT   [0x08]     45      2  idx_to_ptr=0
 *   47                STR_IDX[0x0D]        3     25  "inner_sequence_counter %d"
 *   48                FIELD[0x0B]          4      4  inner_sequence_counter (off=0x0004, hash=0xD0B76C4E)
 *   49              CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *   50              OPEN_CALL[0x07]      4      0  SE_INC_FIELD hash=0x09391555
 *   51              ONESHOT   [0x08]     50      3  idx_to_ptr=0
 *   52                FIELD[0x0B]          4      4  inner_sequence_counter (off=0x0004, hash=0xD0B76C4E)
 *   53                UINT[0x01]           -      -  1 (0x00000001)
 *   54              CLOSE[0x06]          0      -  (end SE_INC_FIELD)
 *   55              OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   56              MAIN+PTR  [0x89]     55      4  idx_to_ptr=0
 *   57                INT[0x00]            -      -  3 (0x00000003)
 *   58              CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *   59              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   60              ONESHOT   [0x08]     59      1  idx_to_ptr=0
 *   61                STR_IDX[0x0D]        4     21  "inner_sequence_fn end"
 *   62              CLOSE[0x06]          0      -  (end SE_LOG)
 *   63              OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *   64              MAIN      [0x09]     63      5  idx_to_ptr=0
 *   65              CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *   66            CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   67            OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   68            MAIN+PTR  [0x89]     67      4  idx_to_ptr=1
 *   69              INT[0x00]            -      -  5 (0x00000005)
 *   70            CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *   71            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   72            ONESHOT   [0x08]     71      1  idx_to_ptr=0
 *   73              STR_IDX[0x0D]        5     20  "loop_sequence_fn end"
 *   74            CLOSE[0x06]          0      -  (end SE_LOG)
 *   75            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *   76            MAIN      [0x09]     75      5  idx_to_ptr=0
 *   77            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *   78          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   79        CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *   80      CLOSE[0x06]          0      -  (end SE_WHILE)
 *   81    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *   82    OPEN_CALL[0x07]     80      0  SE_FORK_JOIN hash=0xE404E1CF
 *   83    MAIN      [0x09]     82      1  idx_to_ptr=0
 *   84      OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   85      ONESHOT   [0x08]     84      0  idx_to_ptr=0
 *   86        FIELD[0x0B]         12      4  field_test_increment (off=0x000C, hash=0x696CDE6A)
 *   87        UINT[0x01]           -      -  1 (0x00000001)
 *   88      CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   89      OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   90      ONESHOT   [0x08]     89      0  idx_to_ptr=0
 *   91        FIELD[0x0B]         16      4  field_test_limit (off=0x0010, hash=0x1CAA35D8)
 *   92        UINT[0x01]           -      -  10 (0x0000000A)
 *   93      CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   94      OPEN_CALL[0x07]     67      0  SE_WHILE hash=0xA08B6DD3
 *   95      MAIN      [0x09]     94      2  idx_to_ptr=0
 *   96        OPEN_CALL[0x07]      5      0  SE_FIELD_INCREMENT_AND_TEST hash=0x275252DB
 *   97        PRED      [0x0A]     96      1  idx_to_ptr=0
 *   98          FIELD[0x0B]          8      4  field_test_counter (off=0x0008, hash=0x6542B7E7)
 *   99          FIELD[0x0B]         12      4  field_test_increment (off=0x000C, hash=0x696CDE6A)
 *  100          FIELD[0x0B]         16      4  field_test_limit (off=0x0010, hash=0x1CAA35D8)
 *  101        CLOSE[0x06]          0      -  (end SE_FIELD_INCREMENT_AND_TEST)
 *  102        OPEN_CALL[0x07]     58      0  SE_FORK_JOIN hash=0xE404E1CF
 *  103        MAIN      [0x09]    102      1  idx_to_ptr=0
 *  104          OPEN_CALL[0x07]     55      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  105          MAIN      [0x09]    104      3  idx_to_ptr=0
 *  106            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  107            ONESHOT   [0x08]    106      1  idx_to_ptr=0
 *  108              STR_IDX[0x0D]        0     22  "loop_sequence_fn start"
 *  109            CLOSE[0x06]          0      -  (end SE_LOG)
 *  110            OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *  111            ONESHOT   [0x08]    110      2  idx_to_ptr=0
 *  112              STR_IDX[0x0D]        1     25  "outer_sequence_counter %d"
 *  113              FIELD[0x0B]          0      4  outer_sequence_counter (off=0x0000, hash=0x24954557)
 *  114            CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *  115            OPEN_CALL[0x07]      4      0  SE_INC_FIELD hash=0x09391555
 *  116            ONESHOT   [0x08]    115      3  idx_to_ptr=0
 *  117              FIELD[0x0B]          0      4  outer_sequence_counter (off=0x0000, hash=0x24954557)
 *  118              UINT[0x01]           -      -  1 (0x00000001)
 *  119            CLOSE[0x06]          0      -  (end SE_INC_FIELD)
 *  120            OPEN_CALL[0x07]     27      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  121            MAIN      [0x09]    120      3  idx_to_ptr=0
 *  122              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  123              ONESHOT   [0x08]    122      1  idx_to_ptr=0
 *  124                STR_IDX[0x0D]        2     23  "inner_sequence_fn start"
 *  125              CLOSE[0x06]          0      -  (end SE_LOG)
 *  126              OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *  127              ONESHOT   [0x08]    126      2  idx_to_ptr=0
 *  128                STR_IDX[0x0D]        3     25  "inner_sequence_counter %d"
 *  129                FIELD[0x0B]          4      4  inner_sequence_counter (off=0x0004, hash=0xD0B76C4E)
 *  130              CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *  131              OPEN_CALL[0x07]      4      0  SE_INC_FIELD hash=0x09391555
 *  132              ONESHOT   [0x08]    131      3  idx_to_ptr=0
 *  133                FIELD[0x0B]          4      4  inner_sequence_counter (off=0x0004, hash=0xD0B76C4E)
 *  134                UINT[0x01]           -      -  1 (0x00000001)
 *  135              CLOSE[0x06]          0      -  (end SE_INC_FIELD)
 *  136              OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  137              MAIN+PTR  [0x89]    136      4  idx_to_ptr=2
 *  138                INT[0x00]            -      -  3 (0x00000003)
 *  139              CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  140              OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  141              ONESHOT   [0x08]    140      1  idx_to_ptr=0
 *  142                STR_IDX[0x0D]        4     21  "inner_sequence_fn end"
 *  143              CLOSE[0x06]          0      -  (end SE_LOG)
 *  144              OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *  145              MAIN      [0x09]    144      5  idx_to_ptr=0
 *  146              CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *  147            CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  148            OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  149            MAIN+PTR  [0x89]    148      4  idx_to_ptr=3
 *  150              INT[0x00]            -      -  5 (0x00000005)
 *  151            CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  152            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  153            ONESHOT   [0x08]    152      1  idx_to_ptr=0
 *  154              STR_IDX[0x0D]        5     20  "loop_sequence_fn end"
 *  155            CLOSE[0x06]          0      -  (end SE_LOG)
 *  156            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *  157            MAIN      [0x09]    156      5  idx_to_ptr=0
 *  158            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *  159          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  160        CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  161      CLOSE[0x06]          0      -  (end SE_WHILE)
 *  162    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  163    OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  164    MAIN      [0x09]    163      6  idx_to_ptr=0
 *  165    CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  166  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 167
 */

#endif // LOOP_TEST_DUMP_32_H
