// ============================================================================
// loop_test.h
// Generated S-expression module for loop_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef LOOP_TEST_H
#define LOOP_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "loop_test_records.h"

// Module: loop_test
#define LOOP_TEST_NAME_HASH 0xD1A777D8
#define LOOP_TEST_TREE_COUNT 1
#define LOOP_TEST_RECORD_COUNT 1

// String table
static const char* const loop_test_strings[] = {
    "loop_sequence_fn start",
    "outer_sequence_counter %d",
    "inner_sequence_fn start",
    "inner_sequence_counter %d",
    "inner_sequence_fn end",
    "loop_sequence_fn end"
};
#define LOOP_TEST_STRING_COUNT 6

// Function hashes
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_HASH 0xCEBBEFA4
#define SE_LOG_INT_HASH 0x2442CEA2
#define SE_INC_FIELD_HASH 0x09391555
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_FORK_JOIN_HASH 0xE404E1CF
#define SE_WHILE_HASH 0xA08B6DD3
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_RETURN_PIPELINE_DISABLE_HASH 0x6B7AA500
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74
#define SE_STATE_INCREMENT_AND_TEST_HASH 0x42A88A80
#define SE_FIELD_INCREMENT_AND_TEST_HASH 0x275252DB

// Tree hashes
#define LOOP_TEST_HASH 0xD1A777D8

// Record hashes
#define LOOP_TEST_BLACKBOARD_HASH 0x033C03AC

// Field hashes
#define FIELD_OUTER_SEQUENCE_COUNTER_HASH 0x24954557
#define FIELD_INNER_SEQUENCE_COUNTER_HASH 0xD0B76C4E
#define FIELD_FIELD_TEST_COUNTER_HASH 0x6542B7E7
#define FIELD_FIELD_TEST_INCREMENT_HASH 0x696CDE6A
#define FIELD_FIELD_TEST_LIMIT_HASH 0x1CAA35D8

#ifdef __cplusplus
}
#endif

#endif // LOOP_TEST_H
