// ============================================================================
// complex_sequence_user_functions.h
// User function prototypes for complex_sequence
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef COMPLEX_SEQUENCE_USER_FUNCTIONS_H
#define COMPLEX_SEQUENCE_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif // COMPLEX_SEQUENCE_USER_FUNCTIONS_H
