// ============================================================================
// complex_sequence_dump_32.h
// DEBUG PARAMETER DUMP for complex_sequence
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef COMPLEX_SEQUENCE_DUMP_32_H
#define COMPLEX_SEQUENCE_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: complex_sequence
 * Hash:   0x82E51725
 * Trees:  1
 * Records: 1
 * Strings: 27
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x8D077FBE "event generator start"
 * [0x0001] (  1) hash=0x0BE2E3B6 "event generator iteration %d"
 * [0x0002] (  2) hash=0x72956ECB "event generator end"
 * [0x0003] (  3) hash=0xC8FF10F8 "wait event test start"
 * [0x0004] (  4) hash=0xFF624E69 "wait event test end"
 * [0x0005] (  5) hash=0xC5B442BB "verify time test start"
 * [0x0006] (  6) hash=0x13217B1E "verify timeout expired this is expected"
 * [0x0007] (  7) hash=0x72933995 "waiting for termination due to eladoed time"
 * [0x0008] (  8) hash=0x725EF313 "verify events test start"
 * [0x0009] (  9) hash=0xA98F1A3D "waiting for termination due to elapsed events"
 * [0x000A] ( 10) hash=0xC581F15F "condition generator start"
 * [0x000B] ( 11) hash=0xBD6995CF "condition generator set 0,0"
 * [0x000C] ( 12) hash=0xDDE415E4 "condition generator set 1,0"
 * [0x000D] ( 13) hash=0xDEE41777 "condition generator set 1,1"
 * [0x000E] ( 14) hash=0xBC69943C "condition generator set 0,1"
 * [0x000F] ( 15) hash=0x66736E2A "condition generator end"
 * [0x0010] ( 16) hash=0x84856868 "complex sequence test start"
 * [0x0011] ( 17) hash=0x39182660 "error function 1 when high condition is expected and will produce a reset"
 * [0x0012] ( 18) hash=0x92F1913C "complex sequence pass test 1"
 * [0x0013] ( 19) hash=0x08B5C71F "error function 2 when low condition is expected and will produce a terminate"
 * [0x0014] ( 20) hash=0x95F195F5 "complex sequence pass test 2"
 * [0x0015] ( 21) hash=0xA6586246 "waiting for error actions"
 * [0x0016] ( 22) hash=0xD32A6B10 "wait timeout terminate test start"
 * [0x0017] ( 23) hash=0x3E36D148 "waiting for timeout"
 * [0x0018] ( 24) hash=0x3C1A62FC "wait timeout resettest start"
 * [0x0019] ( 25) hash=0xC9604B74 "wait normal timeout test start"
 * [0x001A] ( 26) hash=0x8ACEB27B "ending timeout test"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xCEBBEFA4 SE_LOG
 *   [0x0001] ( 1) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0002] ( 2) hash=0x2442CEA2 SE_LOG_INT
 *   [0x0003] ( 3) hash=0xCF729BCE SE_QUEUE_EVENT
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0xE404E1CF SE_FORK_JOIN
 *   [0x0002] ( 2) hash=0x0A24332A SE_FORK
 *   [0x0003] ( 3) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0004] ( 4) hash=0xA08B6DD3 SE_WHILE
 *   [0x0005] ( 5) hash=0xA60CE767 SE_TIME_DELAY
 *   [0x0006] ( 6) hash=0x6B7AA500 SE_RETURN_PIPELINE_DISABLE
 *   [0x0007] ( 7) hash=0xAD4917EC SE_WAIT_EVENT
 *   [0x0008] ( 8) hash=0x0D3E0C4F SE_VERIFY_AND_CHECK_ELAPSED_TIME
 *   [0x0009] ( 9) hash=0x5A902F85 SE_RETURN_PIPELINE_CONTINUE
 *   [0x000A] (10) hash=0x1C4FF9A3 SE_VERIFY_AND_CHECK_ELAPSED_EVENTS
 *   [0x000B] (11) hash=0x0C3460EB SE_TICK_DELAY
 *   [0x000C] (12) hash=0x0933AC9B SE_RETURN_PIPELINE_TERMINATE
 *   [0x000D] (13) hash=0xDD7F6663 SE_WAIT
 *   [0x000E] (14) hash=0xC1DED4CF SE_VERIFY
 *   [0x000F] (15) hash=0xA16E37EF SE_WAIT_TIMEOUT
 *   [0x0010] (16) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *
 * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):
 *   [0x0000] ( 0) hash=0x275252DB SE_FIELD_INCREMENT_AND_TEST
 *   [0x0001] ( 1) hash=0xD9FBED0D SE_FIELD_EQ
 *   [0x0002] ( 2) hash=0x77C35775 SE_FALSE
 *   [0x0003] ( 3) hash=0x0C125BC2 SE_TRUE
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: complex_sequence_blackboard (size=24, align=4, hash=0x81CA0247)
 *   [ 0] off=0x0000 size= 4 hash=0xD3D4D487 complex_sequence_condition_1
 *   [ 1] off=0x0004 size= 4 hash=0xD4D4D61A complex_sequence_condition_2
 *   [ 2] off=0x0008 size= 4 hash=0x8770994C event_field
 *   [ 3] off=0x000C size= 4 hash=0x6542B7E7 field_test_counter
 *   [ 4] off=0x0010 size= 4 hash=0x696CDE6A field_test_increment
 *   [ 5] off=0x0014 size= 4 hash=0x1CAA35D8 field_test_limit
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: complex_sequence_test
 *   hash=0x4800A716 nodes=119 ptrs=15
 *   record=complex_sequence_blackboard (hash=0x81CA0247)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    473      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]     85      0  SE_FORK_JOIN hash=0xE404E1CF
 *    3    MAIN      [0x09]      2      1  idx_to_ptr=0
 *    4      OPEN_CALL[0x07]     82      0  SE_FORK hash=0x0A24332A
 *    5      MAIN      [0x09]      4      2  idx_to_ptr=0
 *    6        OPEN_CALL[0x07]     60      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *    7        MAIN      [0x09]      6      3  idx_to_ptr=0
 *    8          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    9          ONESHOT   [0x08]      8      0  idx_to_ptr=0
 *   10            STR_IDX[0x0D]        0     21  "event generator start"
 *   11          CLOSE[0x06]          0      -  (end SE_LOG)
 *   12          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   13          ONESHOT   [0x08]     12      1  idx_to_ptr=0
 *   14            FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *   15            UINT[0x01]           -      -  0 (0x00000000)
 *   16          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   17          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   18          ONESHOT   [0x08]     17      1  idx_to_ptr=0
 *   19            FIELD[0x0B]         16      4  field_test_increment (off=0x0010, hash=0x696CDE6A)
 *   20            UINT[0x01]           -      -  1 (0x00000001)
 *   21          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   22          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   23          ONESHOT   [0x08]     22      1  idx_to_ptr=0
 *   24            FIELD[0x0B]         20      4  field_test_limit (off=0x0014, hash=0x1CAA35D8)
 *   25            UINT[0x01]           -      -  10 (0x0000000A)
 *   26          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   27          OPEN_CALL[0x07]     31      0  SE_WHILE hash=0xA08B6DD3
 *   28          MAIN      [0x09]     27      4  idx_to_ptr=0
 *   29            OPEN_CALL[0x07]      5      0  SE_FIELD_INCREMENT_AND_TEST hash=0x275252DB
 *   30            PRED      [0x0A]     29      0  idx_to_ptr=0
 *   31              FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *   32              FIELD[0x0B]         16      4  field_test_increment (off=0x0010, hash=0x696CDE6A)
 *   33              FIELD[0x0B]         20      4  field_test_limit (off=0x0014, hash=0x1CAA35D8)
 *   34            CLOSE[0x06]          0      -  (end SE_FIELD_INCREMENT_AND_TEST)
 *   35            OPEN_CALL[0x07]     22      0  SE_FORK_JOIN hash=0xE404E1CF
 *   36            MAIN      [0x09]     35      1  idx_to_ptr=0
 *   37              OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *   38              ONESHOT   [0x08]     37      2  idx_to_ptr=0
 *   39                STR_IDX[0x0D]        1     28  "event generator iteration %d"
 *   40                FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *   41              CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *   42              OPEN_CALL[0x07]      3      0  SE_TIME_DELAY hash=0xA60CE767
 *   43              MAIN+PTR  [0x89]     42      5  idx_to_ptr=0
 *   44                FLOAT[0x02]          -      -  1
 *   45              CLOSE[0x06]          0      -  (end SE_TIME_DELAY)
 *   46              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   47              ONESHOT   [0x08]     46      1  idx_to_ptr=0
 *   48                FIELD[0x0B]          8      4  event_field (off=0x0008, hash=0x8770994C)
 *   49                FLOAT[0x02]          -      -  10.25
 *   50              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   51              OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *   52              ONESHOT   [0x08]     51      3  idx_to_ptr=0
 *   53                UINT[0x01]           -      -  1 (0x00000001)
 *   54                UINT[0x01]           -      -  43 (0x0000002B)
 *   55                FIELD[0x0B]          8      4  event_field (off=0x0008, hash=0x8770994C)
 *   56              CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *   57            CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *   58          CLOSE[0x06]          0      -  (end SE_WHILE)
 *   59          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   60          ONESHOT   [0x08]     59      0  idx_to_ptr=0
 *   61            STR_IDX[0x0D]        2     19  "event generator end"
 *   62          CLOSE[0x06]          0      -  (end SE_LOG)
 *   63          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *   64          MAIN      [0x09]     63      6  idx_to_ptr=0
 *   65          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *   66        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   67        OPEN_CALL[0x07]     18      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   68        MAIN      [0x09]     67      3  idx_to_ptr=0
 *   69          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   70          ONESHOT   [0x08]     69      0  idx_to_ptr=0
 *   71            STR_IDX[0x0D]        3     21  "wait event test start"
 *   72          CLOSE[0x06]          0      -  (end SE_LOG)
 *   73          OPEN_CALL[0x07]      4      0  SE_WAIT_EVENT hash=0xAD4917EC
 *   74          MAIN+PTR  [0x89]     73      7  idx_to_ptr=1
 *   75            UINT[0x01]           -      -  43 (0x0000002B)
 *   76            UINT[0x01]           -      -  10 (0x0000000A)
 *   77          CLOSE[0x06]          0      -  (end SE_WAIT_EVENT)
 *   78          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   79          ONESHOT   [0x08]     78      0  idx_to_ptr=0
 *   80            STR_IDX[0x0D]        4     19  "wait event test end"
 *   81          CLOSE[0x06]          0      -  (end SE_LOG)
 *   82          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *   83          MAIN      [0x09]     82      6  idx_to_ptr=0
 *   84          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *   85        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   86      CLOSE[0x06]          0      -  (end SE_FORK)
 *   87    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *   88    OPEN_CALL[0x07]     25      0  SE_FORK_JOIN hash=0xE404E1CF
 *   89    MAIN      [0x09]     88      1  idx_to_ptr=0
 *   90      OPEN_CALL[0x07]     22      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   91      MAIN      [0x09]     90      3  idx_to_ptr=0
 *   92        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   93        ONESHOT   [0x08]     92      0  idx_to_ptr=0
 *   94          STR_IDX[0x0D]        5     22  "verify time test start"
 *   95        CLOSE[0x06]          0      -  (end SE_LOG)
 *   96        OPEN_CALL[0x07]      8      0  SE_VERIFY_AND_CHECK_ELAPSED_TIME hash=0x0D3E0C4F
 *   97        MAIN+PTR  [0x89]     96      8  idx_to_ptr=2
 *   98          FLOAT[0x02]          -      -  5
 *   99          INT[0x00]            -      -  0 (0x00000000)
 *  100          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  101          ONESHOT   [0x08]    100      0  idx_to_ptr=0
 *  102            STR_IDX[0x0D]        6     39  "verify timeout expired this is expected"
 *  103          CLOSE[0x06]          0      -  (end SE_LOG)
 *  104        CLOSE[0x06]          0      -  (end SE_VERIFY_AND_CHECK_ELAPSED_TIME)
 *  105        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  106        ONESHOT   [0x08]    105      0  idx_to_ptr=0
 *  107          STR_IDX[0x0D]        7     43  "waiting for termination due to eladoe..."
 *  108        CLOSE[0x06]          0      -  (end SE_LOG)
 *  109        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_CONTINUE hash=0x5A902F85
 *  110        MAIN      [0x09]    109      9  idx_to_ptr=0
 *  111        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_CONTINUE)
 *  112      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  113    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  114    OPEN_CALL[0x07]     90      0  SE_FORK_JOIN hash=0xE404E1CF
 *  115    MAIN      [0x09]    114      1  idx_to_ptr=0
 *  116      OPEN_CALL[0x07]     87      0  SE_FORK hash=0x0A24332A
 *  117      MAIN      [0x09]    116      2  idx_to_ptr=0
 *  118        OPEN_CALL[0x07]     60      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  119        MAIN      [0x09]    118      3  idx_to_ptr=0
 *  120          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  121          ONESHOT   [0x08]    120      0  idx_to_ptr=0
 *  122            STR_IDX[0x0D]        0     21  "event generator start"
 *  123          CLOSE[0x06]          0      -  (end SE_LOG)
 *  124          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  125          ONESHOT   [0x08]    124      1  idx_to_ptr=0
 *  126            FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *  127            UINT[0x01]           -      -  0 (0x00000000)
 *  128          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  129          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  130          ONESHOT   [0x08]    129      1  idx_to_ptr=0
 *  131            FIELD[0x0B]         16      4  field_test_increment (off=0x0010, hash=0x696CDE6A)
 *  132            UINT[0x01]           -      -  1 (0x00000001)
 *  133          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  134          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  135          ONESHOT   [0x08]    134      1  idx_to_ptr=0
 *  136            FIELD[0x0B]         20      4  field_test_limit (off=0x0014, hash=0x1CAA35D8)
 *  137            UINT[0x01]           -      -  10 (0x0000000A)
 *  138          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  139          OPEN_CALL[0x07]     31      0  SE_WHILE hash=0xA08B6DD3
 *  140          MAIN      [0x09]    139      4  idx_to_ptr=0
 *  141            OPEN_CALL[0x07]      5      0  SE_FIELD_INCREMENT_AND_TEST hash=0x275252DB
 *  142            PRED      [0x0A]    141      0  idx_to_ptr=0
 *  143              FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *  144              FIELD[0x0B]         16      4  field_test_increment (off=0x0010, hash=0x696CDE6A)
 *  145              FIELD[0x0B]         20      4  field_test_limit (off=0x0014, hash=0x1CAA35D8)
 *  146            CLOSE[0x06]          0      -  (end SE_FIELD_INCREMENT_AND_TEST)
 *  147            OPEN_CALL[0x07]     22      0  SE_FORK_JOIN hash=0xE404E1CF
 *  148            MAIN      [0x09]    147      1  idx_to_ptr=0
 *  149              OPEN_CALL[0x07]      4      0  SE_LOG_INT hash=0x2442CEA2
 *  150              ONESHOT   [0x08]    149      2  idx_to_ptr=0
 *  151                STR_IDX[0x0D]        1     28  "event generator iteration %d"
 *  152                FIELD[0x0B]         12      4  field_test_counter (off=0x000C, hash=0x6542B7E7)
 *  153              CLOSE[0x06]          0      -  (end SE_LOG_INT)
 *  154              OPEN_CALL[0x07]      3      0  SE_TIME_DELAY hash=0xA60CE767
 *  155              MAIN+PTR  [0x89]    154      5  idx_to_ptr=3
 *  156                FLOAT[0x02]          -      -  1
 *  157              CLOSE[0x06]          0      -  (end SE_TIME_DELAY)
 *  158              OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  159              ONESHOT   [0x08]    158      1  idx_to_ptr=0
 *  160                FIELD[0x0B]          8      4  event_field (off=0x0008, hash=0x8770994C)
 *  161                FLOAT[0x02]          -      -  10.25
 *  162              CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  163              OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  164              ONESHOT   [0x08]    163      3  idx_to_ptr=0
 *  165                UINT[0x01]           -      -  1 (0x00000001)
 *  166                UINT[0x01]           -      -  43 (0x0000002B)
 *  167                FIELD[0x0B]          8      4  event_field (off=0x0008, hash=0x8770994C)
 *  168              CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  169            CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  170          CLOSE[0x06]          0      -  (end SE_WHILE)
 *  171          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  172          ONESHOT   [0x08]    171      0  idx_to_ptr=0
 *  173            STR_IDX[0x0D]        2     19  "event generator end"
 *  174          CLOSE[0x06]          0      -  (end SE_LOG)
 *  175          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *  176          MAIN      [0x09]    175      6  idx_to_ptr=0
 *  177          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *  178        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  179        OPEN_CALL[0x07]     23      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  180        MAIN      [0x09]    179      3  idx_to_ptr=0
 *  181          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  182          ONESHOT   [0x08]    181      0  idx_to_ptr=0
 *  183            STR_IDX[0x0D]        8     24  "verify events test start"
 *  184          CLOSE[0x06]          0      -  (end SE_LOG)
 *  185          OPEN_CALL[0x07]      9      0  SE_VERIFY_AND_CHECK_ELAPSED_EVENTS hash=0x1C4FF9A3
 *  186          MAIN+PTR  [0x89]    185     10  idx_to_ptr=4
 *  187            UINT[0x01]           -      -  43 (0x0000002B)
 *  188            UINT[0x01]           -      -  9 (0x00000009)
 *  189            INT[0x00]            -      -  0 (0x00000000)
 *  190            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  191            ONESHOT   [0x08]    190      0  idx_to_ptr=0
 *  192              STR_IDX[0x0D]        6     39  "verify timeout expired this is expected"
 *  193            CLOSE[0x06]          0      -  (end SE_LOG)
 *  194          CLOSE[0x06]          0      -  (end SE_VERIFY_AND_CHECK_ELAPSED_EVENTS)
 *  195          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  196          ONESHOT   [0x08]    195      0  idx_to_ptr=0
 *  197            STR_IDX[0x0D]        9     45  "waiting for termination due to elapse..."
 *  198          CLOSE[0x06]          0      -  (end SE_LOG)
 *  199          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_CONTINUE hash=0x5A902F85
 *  200          MAIN      [0x09]    199      9  idx_to_ptr=0
 *  201          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_CONTINUE)
 *  202        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  203      CLOSE[0x06]          0      -  (end SE_FORK)
 *  204    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  205    OPEN_CALL[0x07]    176      0  SE_FORK_JOIN hash=0xE404E1CF
 *  206    MAIN      [0x09]    205      1  idx_to_ptr=0
 *  207      OPEN_CALL[0x07]    173      0  SE_FORK hash=0x0A24332A
 *  208      MAIN      [0x09]    207      2  idx_to_ptr=0
 *  209        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  210        ONESHOT   [0x08]    209      1  idx_to_ptr=0
 *  211          FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  212          UINT[0x01]           -      -  0 (0x00000000)
 *  213        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  214        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  215        ONESHOT   [0x08]    214      1  idx_to_ptr=0
 *  216          FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  217          UINT[0x01]           -      -  0 (0x00000000)
 *  218        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  219        OPEN_CALL[0x07]     96      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  220        MAIN      [0x09]    219      3  idx_to_ptr=0
 *  221          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  222          ONESHOT   [0x08]    221      0  idx_to_ptr=0
 *  223            STR_IDX[0x0D]       10     25  "condition generator start"
 *  224          CLOSE[0x06]          0      -  (end SE_LOG)
 *  225          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  226          ONESHOT   [0x08]    225      1  idx_to_ptr=0
 *  227            FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  228            UINT[0x01]           -      -  0 (0x00000000)
 *  229          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  230          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  231          ONESHOT   [0x08]    230      1  idx_to_ptr=0
 *  232            FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  233            UINT[0x01]           -      -  0 (0x00000000)
 *  234          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  235          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  236          ONESHOT   [0x08]    235      0  idx_to_ptr=0
 *  237            STR_IDX[0x0D]       11     27  "condition generator set 0,0"
 *  238          CLOSE[0x06]          0      -  (end SE_LOG)
 *  239          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  240          MAIN+PTR  [0x89]    239     11  idx_to_ptr=5
 *  241            INT[0x00]            -      -  10 (0x0000000A)
 *  242          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  243          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  244          ONESHOT   [0x08]    243      1  idx_to_ptr=0
 *  245            FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  246            UINT[0x01]           -      -  1 (0x00000001)
 *  247          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  248          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  249          ONESHOT   [0x08]    248      0  idx_to_ptr=0
 *  250            STR_IDX[0x0D]       12     27  "condition generator set 1,0"
 *  251          CLOSE[0x06]          0      -  (end SE_LOG)
 *  252          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  253          MAIN+PTR  [0x89]    252     11  idx_to_ptr=6
 *  254            INT[0x00]            -      -  10 (0x0000000A)
 *  255          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  256          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  257          ONESHOT   [0x08]    256      1  idx_to_ptr=0
 *  258            FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  259            UINT[0x01]           -      -  1 (0x00000001)
 *  260          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  261          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  262          ONESHOT   [0x08]    261      0  idx_to_ptr=0
 *  263            STR_IDX[0x0D]       13     27  "condition generator set 1,1"
 *  264          CLOSE[0x06]          0      -  (end SE_LOG)
 *  265          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  266          MAIN+PTR  [0x89]    265     11  idx_to_ptr=7
 *  267            INT[0x00]            -      -  10 (0x0000000A)
 *  268          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  269          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  270          ONESHOT   [0x08]    269      1  idx_to_ptr=0
 *  271            FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  272            UINT[0x01]           -      -  0 (0x00000000)
 *  273          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  274          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  275          ONESHOT   [0x08]    274      0  idx_to_ptr=0
 *  276            STR_IDX[0x0D]       14     27  "condition generator set 0,1"
 *  277          CLOSE[0x06]          0      -  (end SE_LOG)
 *  278          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  279          MAIN+PTR  [0x89]    278     11  idx_to_ptr=8
 *  280            INT[0x00]            -      -  10 (0x0000000A)
 *  281          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  282          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  283          ONESHOT   [0x08]    282      1  idx_to_ptr=0
 *  284            FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  285            UINT[0x01]           -      -  1 (0x00000001)
 *  286          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  287          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  288          ONESHOT   [0x08]    287      0  idx_to_ptr=0
 *  289            STR_IDX[0x0D]       13     27  "condition generator set 1,1"
 *  290          CLOSE[0x06]          0      -  (end SE_LOG)
 *  291          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  292          MAIN+PTR  [0x89]    291     11  idx_to_ptr=9
 *  293            INT[0x00]            -      -  10 (0x0000000A)
 *  294          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  295          OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  296          ONESHOT   [0x08]    295      1  idx_to_ptr=0
 *  297            FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  298            UINT[0x01]           -      -  0 (0x00000000)
 *  299          CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  300          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  301          ONESHOT   [0x08]    300      0  idx_to_ptr=0
 *  302            STR_IDX[0x0D]       12     27  "condition generator set 1,0"
 *  303          CLOSE[0x06]          0      -  (end SE_LOG)
 *  304          OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  305          MAIN+PTR  [0x89]    304     11  idx_to_ptr=10
 *  306            INT[0x00]            -      -  10 (0x0000000A)
 *  307          CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  308          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  309          ONESHOT   [0x08]    308      0  idx_to_ptr=0
 *  310            STR_IDX[0x0D]       15     23  "condition generator end"
 *  311          CLOSE[0x06]          0      -  (end SE_LOG)
 *  312          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_TERMINATE hash=0x0933AC9B
 *  313          MAIN      [0x09]    312     12  idx_to_ptr=0
 *  314          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_TERMINATE)
 *  315        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  316        OPEN_CALL[0x07]     63      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  317        MAIN      [0x09]    316      3  idx_to_ptr=0
 *  318          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  319          ONESHOT   [0x08]    318      0  idx_to_ptr=0
 *  320            STR_IDX[0x0D]       16     27  "complex sequence test start"
 *  321          CLOSE[0x06]          0      -  (end SE_LOG)
 *  322          OPEN_CALL[0x07]      7      0  SE_WAIT hash=0xDD7F6663
 *  323          MAIN      [0x09]    322     13  idx_to_ptr=0
 *  324            OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  325            PRED      [0x0A]    324      1  idx_to_ptr=0
 *  326              FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  327              UINT[0x01]           -      -  1 (0x00000001)
 *  328            CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  329          CLOSE[0x06]          0      -  (end SE_WAIT)
 *  330          OPEN_CALL[0x07]     12      0  SE_VERIFY hash=0xC1DED4CF
 *  331          MAIN      [0x09]    330     14  idx_to_ptr=0
 *  332            OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  333            PRED      [0x0A]    332      1  idx_to_ptr=0
 *  334              FIELD[0x0B]          0      4  complex_sequence_condition_1 (off=0x0000, hash=0xD3D4D487)
 *  335              UINT[0x01]           -      -  1 (0x00000001)
 *  336            CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  337            INT[0x00]            -      -  1 (0x00000001)
 *  338            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  339            ONESHOT   [0x08]    338      0  idx_to_ptr=0
 *  340              STR_IDX[0x0D]       17     73  "error function 1 when high condition ..."
 *  341            CLOSE[0x06]          0      -  (end SE_LOG)
 *  342          CLOSE[0x06]          0      -  (end SE_VERIFY)
 *  343          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  344          ONESHOT   [0x08]    343      0  idx_to_ptr=0
 *  345            STR_IDX[0x0D]       18     28  "complex sequence pass test 1"
 *  346          CLOSE[0x06]          0      -  (end SE_LOG)
 *  347          OPEN_CALL[0x07]      7      0  SE_WAIT hash=0xDD7F6663
 *  348          MAIN      [0x09]    347     13  idx_to_ptr=0
 *  349            OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  350            PRED      [0x0A]    349      1  idx_to_ptr=0
 *  351              FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  352              UINT[0x01]           -      -  1 (0x00000001)
 *  353            CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  354          CLOSE[0x06]          0      -  (end SE_WAIT)
 *  355          OPEN_CALL[0x07]     12      0  SE_VERIFY hash=0xC1DED4CF
 *  356          MAIN      [0x09]    355     14  idx_to_ptr=0
 *  357            OPEN_CALL[0x07]      4      0  SE_FIELD_EQ hash=0xD9FBED0D
 *  358            PRED      [0x0A]    357      1  idx_to_ptr=0
 *  359              FIELD[0x0B]          4      4  complex_sequence_condition_2 (off=0x0004, hash=0xD4D4D61A)
 *  360              UINT[0x01]           -      -  1 (0x00000001)
 *  361            CLOSE[0x06]          0      -  (end SE_FIELD_EQ)
 *  362            INT[0x00]            -      -  0 (0x00000000)
 *  363            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  364            ONESHOT   [0x08]    363      0  idx_to_ptr=0
 *  365              STR_IDX[0x0D]       19     76  "error function 2 when low condition i..."
 *  366            CLOSE[0x06]          0      -  (end SE_LOG)
 *  367          CLOSE[0x06]          0      -  (end SE_VERIFY)
 *  368          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  369          ONESHOT   [0x08]    368      0  idx_to_ptr=0
 *  370            STR_IDX[0x0D]       20     28  "complex sequence pass test 2"
 *  371          CLOSE[0x06]          0      -  (end SE_LOG)
 *  372          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  373          ONESHOT   [0x08]    372      0  idx_to_ptr=0
 *  374            STR_IDX[0x0D]       21     25  "waiting for error actions"
 *  375          CLOSE[0x06]          0      -  (end SE_LOG)
 *  376          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_CONTINUE hash=0x5A902F85
 *  377          MAIN      [0x09]    376      9  idx_to_ptr=0
 *  378          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_CONTINUE)
 *  379        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  380      CLOSE[0x06]          0      -  (end SE_FORK)
 *  381    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  382    OPEN_CALL[0x07]     87      0  SE_FORK_JOIN hash=0xE404E1CF
 *  383    MAIN      [0x09]    382      1  idx_to_ptr=0
 *  384      OPEN_CALL[0x07]     84      0  SE_FORK hash=0x0A24332A
 *  385      MAIN      [0x09]    384      2  idx_to_ptr=0
 *  386        OPEN_CALL[0x07]     25      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  387        MAIN      [0x09]    386      3  idx_to_ptr=0
 *  388          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  389          ONESHOT   [0x08]    388      0  idx_to_ptr=0
 *  390            STR_IDX[0x0D]       22     33  "wait timeout terminate test start"
 *  391          CLOSE[0x06]          0      -  (end SE_LOG)
 *  392          OPEN_CALL[0x07]     11      0  SE_WAIT_TIMEOUT hash=0xA16E37EF
 *  393          MAIN+PTR  [0x89]    392     15  idx_to_ptr=11
 *  394            OPEN_CALL[0x07]      2      0  SE_FALSE hash=0x77C35775
 *  395            PRED      [0x0A]    394      2  idx_to_ptr=0
 *  396            CLOSE[0x06]          0      -  (end SE_FALSE)
 *  397            FLOAT[0x02]          -      -  5
 *  398            INT[0x00]            -      -  0 (0x00000000)
 *  399            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  400            ONESHOT   [0x08]    399      0  idx_to_ptr=0
 *  401              STR_IDX[0x0D]       19     76  "error function 2 when low condition i..."
 *  402            CLOSE[0x06]          0      -  (end SE_LOG)
 *  403          CLOSE[0x06]          0      -  (end SE_WAIT_TIMEOUT)
 *  404          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  405          ONESHOT   [0x08]    404      0  idx_to_ptr=0
 *  406            STR_IDX[0x0D]       23     19  "waiting for timeout"
 *  407          CLOSE[0x06]          0      -  (end SE_LOG)
 *  408          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_TERMINATE hash=0x0933AC9B
 *  409          MAIN      [0x09]    408     12  idx_to_ptr=0
 *  410          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_TERMINATE)
 *  411        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  412        OPEN_CALL[0x07]     25      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  413        MAIN      [0x09]    412      3  idx_to_ptr=0
 *  414          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  415          ONESHOT   [0x08]    414      0  idx_to_ptr=0
 *  416            STR_IDX[0x0D]       24     28  "wait timeout resettest start"
 *  417          CLOSE[0x06]          0      -  (end SE_LOG)
 *  418          OPEN_CALL[0x07]     11      0  SE_WAIT_TIMEOUT hash=0xA16E37EF
 *  419          MAIN+PTR  [0x89]    418     15  idx_to_ptr=12
 *  420            OPEN_CALL[0x07]      2      0  SE_FALSE hash=0x77C35775
 *  421            PRED      [0x0A]    420      2  idx_to_ptr=0
 *  422            CLOSE[0x06]          0      -  (end SE_FALSE)
 *  423            FLOAT[0x02]          -      -  2
 *  424            INT[0x00]            -      -  1 (0x00000001)
 *  425            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  426            ONESHOT   [0x08]    425      0  idx_to_ptr=0
 *  427              STR_IDX[0x0D]       17     73  "error function 1 when high condition ..."
 *  428            CLOSE[0x06]          0      -  (end SE_LOG)
 *  429          CLOSE[0x06]          0      -  (end SE_WAIT_TIMEOUT)
 *  430          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  431          ONESHOT   [0x08]    430      0  idx_to_ptr=0
 *  432            STR_IDX[0x0D]       23     19  "waiting for timeout"
 *  433          CLOSE[0x06]          0      -  (end SE_LOG)
 *  434          OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_TERMINATE hash=0x0933AC9B
 *  435          MAIN      [0x09]    434     12  idx_to_ptr=0
 *  436          CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_TERMINATE)
 *  437        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  438        OPEN_CALL[0x07]     29      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  439        MAIN      [0x09]    438      3  idx_to_ptr=0
 *  440          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  441          ONESHOT   [0x08]    440      0  idx_to_ptr=0
 *  442            STR_IDX[0x0D]       25     30  "wait normal timeout test start"
 *  443          CLOSE[0x06]          0      -  (end SE_LOG)
 *  444          OPEN_CALL[0x07]     11      0  SE_WAIT_TIMEOUT hash=0xA16E37EF
 *  445          MAIN+PTR  [0x89]    444     15  idx_to_ptr=13
 *  446            OPEN_CALL[0x07]      2      0  SE_TRUE hash=0x0C125BC2
 *  447            PRED      [0x0A]    446      3  idx_to_ptr=0
 *  448            CLOSE[0x06]          0      -  (end SE_TRUE)
 *  449            FLOAT[0x02]          -      -  5
 *  450            INT[0x00]            -      -  0 (0x00000000)
 *  451            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  452            ONESHOT   [0x08]    451      0  idx_to_ptr=0
 *  453              STR_IDX[0x0D]       17     73  "error function 1 when high condition ..."
 *  454            CLOSE[0x06]          0      -  (end SE_LOG)
 *  455          CLOSE[0x06]          0      -  (end SE_WAIT_TIMEOUT)
 *  456          OPEN_CALL[0x07]      3      0  SE_TIME_DELAY hash=0xA60CE767
 *  457          MAIN+PTR  [0x89]    456      5  idx_to_ptr=14
 *  458            FLOAT[0x02]          -      -  10
 *  459          CLOSE[0x06]          0      -  (end SE_TIME_DELAY)
 *  460          OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  461          ONESHOT   [0x08]    460      0  idx_to_ptr=0
 *  462            STR_IDX[0x0D]       26     19  "ending timeout test"
 *  463          CLOSE[0x06]          0      -  (end SE_LOG)
 *  464          OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  465          MAIN      [0x09]    464     16  idx_to_ptr=0
 *  466          CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  467        CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  468      CLOSE[0x06]          0      -  (end SE_FORK)
 *  469    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *  470    OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  471    MAIN      [0x09]    470     16  idx_to_ptr=0
 *  472    CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  473  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 474
 */

#endif // COMPLEX_SEQUENCE_DUMP_32_H
