// ============================================================================
// complex_sequence.h
// Generated S-expression module for complex_sequence
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef COMPLEX_SEQUENCE_H
#define COMPLEX_SEQUENCE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "complex_sequence_records.h"

// Module: complex_sequence
#define COMPLEX_SEQUENCE_NAME_HASH 0x82E51725
#define COMPLEX_SEQUENCE_TREE_COUNT 1
#define COMPLEX_SEQUENCE_RECORD_COUNT 1

// String table
static const char* const complex_sequence_strings[] = {
    "event generator start",
    "event generator iteration %d",
    "event generator end",
    "wait event test start",
    "wait event test end",
    "verify time test start",
    "verify timeout expired this is expected",
    "waiting for termination due to eladoed time",
    "verify events test start",
    "waiting for termination due to elapsed events",
    "condition generator start",
    "condition generator set 0,0",
    "condition generator set 1,0",
    "condition generator set 1,1",
    "condition generator set 0,1",
    "condition generator end",
    "complex sequence test start",
    "error function 1 when high condition is expected and will produce a reset",
    "complex sequence pass test 1",
    "error function 2 when low condition is expected and will produce a terminate",
    "complex sequence pass test 2",
    "waiting for error actions",
    "wait timeout terminate test start",
    "waiting for timeout",
    "wait timeout resettest start",
    "wait normal timeout test start",
    "ending timeout test"
};
#define COMPLEX_SEQUENCE_STRING_COUNT 27

// Function hashes
#define SE_LOG_HASH 0xCEBBEFA4
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_INT_HASH 0x2442CEA2
#define SE_QUEUE_EVENT_HASH 0xCF729BCE
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_FORK_JOIN_HASH 0xE404E1CF
#define SE_FORK_HASH 0x0A24332A
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_WHILE_HASH 0xA08B6DD3
#define SE_TIME_DELAY_HASH 0xA60CE767
#define SE_RETURN_PIPELINE_DISABLE_HASH 0x6B7AA500
#define SE_WAIT_EVENT_HASH 0xAD4917EC
#define SE_VERIFY_AND_CHECK_ELAPSED_TIME_HASH 0x0D3E0C4F
#define SE_RETURN_PIPELINE_CONTINUE_HASH 0x5A902F85
#define SE_VERIFY_AND_CHECK_ELAPSED_EVENTS_HASH 0x1C4FF9A3
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_RETURN_PIPELINE_TERMINATE_HASH 0x0933AC9B
#define SE_WAIT_HASH 0xDD7F6663
#define SE_VERIFY_HASH 0xC1DED4CF
#define SE_WAIT_TIMEOUT_HASH 0xA16E37EF
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74
#define SE_FIELD_INCREMENT_AND_TEST_HASH 0x275252DB
#define SE_FIELD_EQ_HASH 0xD9FBED0D
#define SE_FALSE_HASH 0x77C35775
#define SE_TRUE_HASH 0x0C125BC2

// Tree hashes
#define COMPLEX_SEQUENCE_TEST_HASH 0x4800A716

// Record hashes
#define COMPLEX_SEQUENCE_BLACKBOARD_HASH 0x81CA0247

// Field hashes
#define FIELD_COMPLEX_SEQUENCE_CONDITION_1_HASH 0xD3D4D487
#define FIELD_COMPLEX_SEQUENCE_CONDITION_2_HASH 0xD4D4D61A
#define FIELD_EVENT_FIELD_HASH 0x8770994C
#define FIELD_FIELD_TEST_COUNTER_HASH 0x6542B7E7
#define FIELD_FIELD_TEST_INCREMENT_HASH 0x696CDE6A
#define FIELD_FIELD_TEST_LIMIT_HASH 0x1CAA35D8

#ifdef __cplusplus
}
#endif

#endif // COMPLEX_SEQUENCE_H
