// ============================================================================
// complex_sequence_records.h
// Generated record structures for complex_sequence
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef COMPLEX_SEQUENCE_RECORDS_H
#define COMPLEX_SEQUENCE_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct complex_sequence_blackboard_s complex_sequence_blackboard_t;

// Record: complex_sequence_blackboard (size=24, align=4)
struct complex_sequence_blackboard_s {
    uint32_t complex_sequence_condition_1;  // offset=0, size=4
    uint32_t complex_sequence_condition_2;  // offset=4, size=4
    float event_field;  // offset=8, size=4
    uint32_t field_test_counter;  // offset=12, size=4
    uint32_t field_test_increment;  // offset=16, size=4
    uint32_t field_test_limit;  // offset=20, size=4
};

#endif // COMPLEX_SEQUENCE_RECORDS_H
