// ============================================================================
// basic_primitive_test_module_rom.c
// Generated S-expression module for basic_primitive_test (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "basic_primitive_test.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern void on_bit0_rise(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bit0_fall(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bits_12_rise(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bits_12_fall(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bits_34_rise(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bits_34_fall(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bit5_clear(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void on_bit5_set(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern bool test_bit(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

// Tree: basic_primitive_test (params=159, nodes=47)
static const s_expr_param_t basic_primitive_test_basic_primitive_test_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 158, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 33, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 1, .func_index = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 2 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 2, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 6 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 0 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 6, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 19 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 7, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 10, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 31 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 33, .parent_offset = 34 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 40, .parent_offset = 35 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 11, .func_index = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 10, .parent_offset = 2 },
    { .type = 0x4A, .index_to_pointer = 0, .node_index = 12, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 13, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 14, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 10, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 15, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 18, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 25 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 19, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 20, .func_index = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 21, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 22, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 38 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 40, .parent_offset = 75 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 40, .parent_offset = 76 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 23, .func_index = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 10, .parent_offset = 2 },
    { .type = 0x4A, .index_to_pointer = 0, .node_index = 24, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 25, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 26, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 10, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 27, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 28, .func_index = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 29, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 4, .str_len = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 30, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 25 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 31, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 32, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 33, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 5, .str_len = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 34, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 38 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 40, .parent_offset = 116 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 36, .parent_offset = 117 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 35, .func_index = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 2 },
    { .type = 0x4A, .index_to_pointer = 0, .node_index = 36, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 37, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 9 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 38, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 39, .func_index = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 40, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 6, .str_len = 13 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 41, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 21 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 22 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 42, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 43, .func_index = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 44, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 7, .str_len = 11 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 8 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 45, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 12, .parent_offset = 34 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 36, .parent_offset = 153 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 154 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 46, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 156 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 158, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t basic_primitive_test_trees[] = {
    {
        .name_hash = 0xC0F76968U,
        .record_hash = 0U,
        .params = basic_primitive_test_basic_primitive_test_params,
        .param_count = 159,
        .func_node_count = 47,
        .pointer_count = 0,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t basic_primitive_test_oneshot_fns[] = {
    on_bit0_rise,  // 0: ON_BIT0_RISE
    se_log,  // 1: SE_LOG
    on_bit0_fall,  // 2: ON_BIT0_FALL
    on_bits_12_rise,  // 3: ON_BITS_12_RISE
    on_bits_12_fall,  // 4: ON_BITS_12_FALL
    on_bits_34_rise,  // 5: ON_BITS_34_RISE
    on_bits_34_fall,  // 6: ON_BITS_34_FALL
    on_bit5_clear,  // 7: ON_BIT5_CLEAR
    on_bit5_set  // 8: ON_BIT5_SET
};

static const s_expr_main_fn_t basic_primitive_test_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    se_trigger_on_change,  // 1: SE_TRIGGER_ON_CHANGE
    se_chain_flow,  // 2: SE_CHAIN_FLOW
    se_return_continue  // 3: SE_RETURN_CONTINUE
};

static const s_expr_pred_fn_t basic_primitive_test_pred_fns[] = {
    test_bit,  // 0: TEST_BIT
    se_pred_and,  // 1: SE_PRED_AND
    se_pred_or,  // 2: SE_PRED_OR
    se_pred_not  // 3: SE_PRED_NOT
};

// Top-level ROM handle (M-port)
const s_engine_rom_t basic_primitive_test_module_rom = {
    .name_hash = 0xC0F76968U,
    .is_64bit = false,
    .trees = basic_primitive_test_trees,
    .tree_count = 1,
    .records = NULL,
    .record_count = 0,
    .string_table = basic_primitive_test_strings,
    .string_count = 8,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = basic_primitive_test_oneshot_fns,
    .oneshot_count = 9,
    .main_fns = basic_primitive_test_main_fns,
    .main_count = 4,
    .pred_fns = basic_primitive_test_pred_fns,
    .pred_count = 4,
    .max_func_node_count = 47,
    .max_pointer_count = 0,
    .max_param_count = 159,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

