// ============================================================================
// basic_primitive_test_dump_32.h
// DEBUG PARAMETER DUMP for basic_primitive_test
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef BASIC_PRIMITIVE_TEST_DUMP_32_H
#define BASIC_PRIMITIVE_TEST_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: basic_primitive_test
 * Hash:   0xC0F76968
 * Trees:  1
 * Records: 0
 * Strings: 8
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x13068D30 "ON_BIT0_RISE"
 * [0x0001] (  1) hash=0xF8140330 "ON_BIT0_FALL"
 * [0x0002] (  2) hash=0xFE5ADA37 "ON_BITS_12_RISE"
 * [0x0003] (  3) hash=0x7B832107 "ON_BITS_12_FALL"
 * [0x0004] (  4) hash=0x6B533EF3 "ON_BITS_34_RISE"
 * [0x0005] (  5) hash=0x29423823 "ON_BITS_34_FALL"
 * [0x0006] (  6) hash=0x15953A35 "ON_BIT5_CLEAR"
 * [0x0007] (  7) hash=0xAC23F0C8 "ON_BIT5_SET"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0x13068D30 ON_BIT0_RISE
 *   [0x0001] ( 1) hash=0xCEBBEFA4 SE_LOG
 *   [0x0002] ( 2) hash=0xF8140330 ON_BIT0_FALL
 *   [0x0003] ( 3) hash=0xFE5ADA37 ON_BITS_12_RISE
 *   [0x0004] ( 4) hash=0x7B832107 ON_BITS_12_FALL
 *   [0x0005] ( 5) hash=0x6B533EF3 ON_BITS_34_RISE
 *   [0x0006] ( 6) hash=0x29423823 ON_BITS_34_FALL
 *   [0x0007] ( 7) hash=0x15953A35 ON_BIT5_CLEAR
 *   [0x0008] ( 8) hash=0xAC23F0C8 ON_BIT5_SET
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0x8374277F SE_TRIGGER_ON_CHANGE
 *   [0x0002] ( 2) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0003] ( 3) hash=0xB4243714 SE_RETURN_CONTINUE
 *
 * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):
 *   [0x0000] ( 0) hash=0x2D749139 TEST_BIT
 *   [0x0001] ( 1) hash=0x7C0DF5F3 SE_PRED_AND
 *   [0x0002] ( 2) hash=0x0CF6212F SE_PRED_OR
 *   [0x0003] ( 3) hash=0x217DEB8F SE_PRED_NOT
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: basic_primitive_test
 *   hash=0xC0F76968 nodes=47 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    158      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]     33      0  SE_TRIGGER_ON_CHANGE hash=0x8374277F
 *    3    MAIN      [0x09]      2      1  idx_to_ptr=0
 *    4      INT[0x00]            -      -  0 (0x00000000)
 *    5      OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *    6      PRED      [0x0A]      5      0  idx_to_ptr=0
 *    7        INT[0x00]            -      -  0 (0x00000000)
 *    8      CLOSE[0x06]          0      -  (end TEST_BIT)
 *    9      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   10      MAIN      [0x09]      9      2  idx_to_ptr=0
 *   11        OPEN_CALL[0x07]      2      0  ON_BIT0_RISE hash=0x13068D30
 *   12        ONESHOT   [0x08]     11      0  idx_to_ptr=0
 *   13        CLOSE[0x06]          0      -  (end ON_BIT0_RISE)
 *   14        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   15        ONESHOT   [0x08]     14      1  idx_to_ptr=0
 *   16          STR_IDX[0x0D]        0     12  "ON_BIT0_RISE"
 *   17        CLOSE[0x06]          0      -  (end SE_LOG)
 *   18        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *   19        MAIN      [0x09]     18      3  idx_to_ptr=0
 *   20        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *   21      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   22      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   23      MAIN      [0x09]     22      2  idx_to_ptr=0
 *   24        OPEN_CALL[0x07]      2      0  ON_BIT0_FALL hash=0xF8140330
 *   25        ONESHOT   [0x08]     24      2  idx_to_ptr=0
 *   26        CLOSE[0x06]          0      -  (end ON_BIT0_FALL)
 *   27        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   28        ONESHOT   [0x08]     27      1  idx_to_ptr=0
 *   29          STR_IDX[0x0D]        1     12  "ON_BIT0_FALL"
 *   30        CLOSE[0x06]          0      -  (end SE_LOG)
 *   31        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *   32        MAIN      [0x09]     31      3  idx_to_ptr=0
 *   33        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *   34      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   35    CLOSE[0x06]          0      -  (end SE_TRIGGER_ON_CHANGE)
 *   36    OPEN_CALL[0x07]     40      0  SE_TRIGGER_ON_CHANGE hash=0x8374277F
 *   37    MAIN      [0x09]     36      1  idx_to_ptr=0
 *   38      INT[0x00]            -      -  0 (0x00000000)
 *   39      OPEN_CALL[0x07]     10      0  SE_PRED_AND hash=0x7C0DF5F3
 *   40      PRED+SR   [0x4A]     39      1  idx_to_ptr=0
 *   41        OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *   42        PRED      [0x0A]     41      0  idx_to_ptr=0
 *   43          INT[0x00]            -      -  1 (0x00000001)
 *   44        CLOSE[0x06]          0      -  (end TEST_BIT)
 *   45        OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *   46        PRED      [0x0A]     45      0  idx_to_ptr=0
 *   47          INT[0x00]            -      -  2 (0x00000002)
 *   48        CLOSE[0x06]          0      -  (end TEST_BIT)
 *   49      CLOSE[0x06]          0      -  (end SE_PRED_AND)
 *   50      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   51      MAIN      [0x09]     50      2  idx_to_ptr=0
 *   52        OPEN_CALL[0x07]      2      0  ON_BITS_12_RISE hash=0xFE5ADA37
 *   53        ONESHOT   [0x08]     52      3  idx_to_ptr=0
 *   54        CLOSE[0x06]          0      -  (end ON_BITS_12_RISE)
 *   55        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   56        ONESHOT   [0x08]     55      1  idx_to_ptr=0
 *   57          STR_IDX[0x0D]        2     15  "ON_BITS_12_RISE"
 *   58        CLOSE[0x06]          0      -  (end SE_LOG)
 *   59        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *   60        MAIN      [0x09]     59      3  idx_to_ptr=0
 *   61        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *   62      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   63      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   64      MAIN      [0x09]     63      2  idx_to_ptr=0
 *   65        OPEN_CALL[0x07]      2      0  ON_BITS_12_FALL hash=0x7B832107
 *   66        ONESHOT   [0x08]     65      4  idx_to_ptr=0
 *   67        CLOSE[0x06]          0      -  (end ON_BITS_12_FALL)
 *   68        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   69        ONESHOT   [0x08]     68      1  idx_to_ptr=0
 *   70          STR_IDX[0x0D]        3     15  "ON_BITS_12_FALL"
 *   71        CLOSE[0x06]          0      -  (end SE_LOG)
 *   72        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *   73        MAIN      [0x09]     72      3  idx_to_ptr=0
 *   74        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *   75      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   76    CLOSE[0x06]          0      -  (end SE_TRIGGER_ON_CHANGE)
 *   77    OPEN_CALL[0x07]     40      0  SE_TRIGGER_ON_CHANGE hash=0x8374277F
 *   78    MAIN      [0x09]     77      1  idx_to_ptr=0
 *   79      INT[0x00]            -      -  0 (0x00000000)
 *   80      OPEN_CALL[0x07]     10      0  SE_PRED_OR hash=0x0CF6212F
 *   81      PRED+SR   [0x4A]     80      2  idx_to_ptr=0
 *   82        OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *   83        PRED      [0x0A]     82      0  idx_to_ptr=0
 *   84          INT[0x00]            -      -  3 (0x00000003)
 *   85        CLOSE[0x06]          0      -  (end TEST_BIT)
 *   86        OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *   87        PRED      [0x0A]     86      0  idx_to_ptr=0
 *   88          INT[0x00]            -      -  4 (0x00000004)
 *   89        CLOSE[0x06]          0      -  (end TEST_BIT)
 *   90      CLOSE[0x06]          0      -  (end SE_PRED_OR)
 *   91      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   92      MAIN      [0x09]     91      2  idx_to_ptr=0
 *   93        OPEN_CALL[0x07]      2      0  ON_BITS_34_RISE hash=0x6B533EF3
 *   94        ONESHOT   [0x08]     93      5  idx_to_ptr=0
 *   95        CLOSE[0x06]          0      -  (end ON_BITS_34_RISE)
 *   96        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   97        ONESHOT   [0x08]     96      1  idx_to_ptr=0
 *   98          STR_IDX[0x0D]        4     15  "ON_BITS_34_RISE"
 *   99        CLOSE[0x06]          0      -  (end SE_LOG)
 *  100        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *  101        MAIN      [0x09]    100      3  idx_to_ptr=0
 *  102        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *  103      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  104      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  105      MAIN      [0x09]    104      2  idx_to_ptr=0
 *  106        OPEN_CALL[0x07]      2      0  ON_BITS_34_FALL hash=0x29423823
 *  107        ONESHOT   [0x08]    106      6  idx_to_ptr=0
 *  108        CLOSE[0x06]          0      -  (end ON_BITS_34_FALL)
 *  109        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  110        ONESHOT   [0x08]    109      1  idx_to_ptr=0
 *  111          STR_IDX[0x0D]        5     15  "ON_BITS_34_FALL"
 *  112        CLOSE[0x06]          0      -  (end SE_LOG)
 *  113        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *  114        MAIN      [0x09]    113      3  idx_to_ptr=0
 *  115        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *  116      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  117    CLOSE[0x06]          0      -  (end SE_TRIGGER_ON_CHANGE)
 *  118    OPEN_CALL[0x07]     36      0  SE_TRIGGER_ON_CHANGE hash=0x8374277F
 *  119    MAIN      [0x09]    118      1  idx_to_ptr=0
 *  120      INT[0x00]            -      -  1 (0x00000001)
 *  121      OPEN_CALL[0x07]      6      0  SE_PRED_NOT hash=0x217DEB8F
 *  122      PRED+SR   [0x4A]    121      3  idx_to_ptr=0
 *  123        OPEN_CALL[0x07]      3      0  TEST_BIT hash=0x2D749139
 *  124        PRED      [0x0A]    123      0  idx_to_ptr=0
 *  125          INT[0x00]            -      -  5 (0x00000005)
 *  126        CLOSE[0x06]          0      -  (end TEST_BIT)
 *  127      CLOSE[0x06]          0      -  (end SE_PRED_NOT)
 *  128      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  129      MAIN      [0x09]    128      2  idx_to_ptr=0
 *  130        OPEN_CALL[0x07]      2      0  ON_BIT5_CLEAR hash=0x15953A35
 *  131        ONESHOT   [0x08]    130      7  idx_to_ptr=0
 *  132        CLOSE[0x06]          0      -  (end ON_BIT5_CLEAR)
 *  133        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  134        ONESHOT   [0x08]    133      1  idx_to_ptr=0
 *  135          STR_IDX[0x0D]        6     13  "ON_BIT5_CLEAR"
 *  136        CLOSE[0x06]          0      -  (end SE_LOG)
 *  137        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *  138        MAIN      [0x09]    137      3  idx_to_ptr=0
 *  139        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *  140      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  141      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  142      MAIN      [0x09]    141      2  idx_to_ptr=0
 *  143        OPEN_CALL[0x07]      2      0  ON_BIT5_SET hash=0xAC23F0C8
 *  144        ONESHOT   [0x08]    143      8  idx_to_ptr=0
 *  145        CLOSE[0x06]          0      -  (end ON_BIT5_SET)
 *  146        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  147        ONESHOT   [0x08]    146      1  idx_to_ptr=0
 *  148          STR_IDX[0x0D]        7     11  "ON_BIT5_SET"
 *  149        CLOSE[0x06]          0      -  (end SE_LOG)
 *  150        OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *  151        MAIN      [0x09]    150      3  idx_to_ptr=0
 *  152        CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *  153      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  154    CLOSE[0x06]          0      -  (end SE_TRIGGER_ON_CHANGE)
 *  155    OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *  156    MAIN      [0x09]    155      3  idx_to_ptr=0
 *  157    CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *  158  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 159
 */

#endif // BASIC_PRIMITIVE_TEST_DUMP_32_H
