// ============================================================================
// basic_primitive_test_user_functions.h
// User function prototypes for basic_primitive_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef BASIC_PRIMITIVE_TEST_USER_FUNCTIONS_H
#define BASIC_PRIMITIVE_TEST_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// Oneshot functions
void on_bit0_rise(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bit0_fall(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bits_12_rise(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bits_12_fall(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bits_34_rise(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bits_34_fall(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bit5_clear(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void on_bit5_set(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

// Predicate functions
bool test_bit(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

#ifdef __cplusplus
}
#endif

#endif // BASIC_PRIMITIVE_TEST_USER_FUNCTIONS_H
