// ============================================================================
// basic_primitive_test_user_registration.c
// User function registration for basic_primitive_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "basic_primitive_test.h"
#include "basic_primitive_test_user_functions.h"
#include "s_engine_module.h"

// Oneshot function entries
static s_expr_fn_entry_t basic_primitive_test_oneshot_entries[] = {
    { 0x13068D30, (void*)on_bit0_rise },
    { 0xF8140330, (void*)on_bit0_fall },
    { 0xFE5ADA37, (void*)on_bits_12_rise },
    { 0x7B832107, (void*)on_bits_12_fall },
    { 0x6B533EF3, (void*)on_bits_34_rise },
    { 0x29423823, (void*)on_bits_34_fall },
    { 0x15953A35, (void*)on_bit5_clear },
    { 0xAC23F0C8, (void*)on_bit5_set },
};

static const s_expr_fn_table_t basic_primitive_test_oneshot_table = {
    .entries = basic_primitive_test_oneshot_entries,
    .count = 8
};

// Predicate function entries
static s_expr_fn_entry_t basic_primitive_test_pred_entries[] = {
    { 0x2D749139, (void*)test_bit },
};

static const s_expr_fn_table_t basic_primitive_test_pred_table = {
    .entries = basic_primitive_test_pred_entries,
    .count = 1
};

// Table accessors
const s_expr_fn_table_t* basic_primitive_test_get_oneshot_table(void) {
    return &basic_primitive_test_oneshot_table;
}

const s_expr_fn_table_t* basic_primitive_test_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* basic_primitive_test_get_pred_table(void) {
    return &basic_primitive_test_pred_table;
}

// Register all user functions with module
void basic_primitive_test_register_all(s_expr_module_t* module) {
    s_expr_module_register_oneshot(module, &basic_primitive_test_oneshot_table);
    s_expr_module_register_pred(module, &basic_primitive_test_pred_table);
}
