// ============================================================================
// basic_primitive_test.h
// Generated S-expression module for basic_primitive_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef BASIC_PRIMITIVE_TEST_H
#define BASIC_PRIMITIVE_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"

// Module: basic_primitive_test
#define BASIC_PRIMITIVE_TEST_NAME_HASH 0xC0F76968
#define BASIC_PRIMITIVE_TEST_TREE_COUNT 1
#define BASIC_PRIMITIVE_TEST_RECORD_COUNT 0

// String table
static const char* const basic_primitive_test_strings[] = {
    "ON_BIT0_RISE",
    "ON_BIT0_FALL",
    "ON_BITS_12_RISE",
    "ON_BITS_12_FALL",
    "ON_BITS_34_RISE",
    "ON_BITS_34_FALL",
    "ON_BIT5_CLEAR",
    "ON_BIT5_SET"
};
#define BASIC_PRIMITIVE_TEST_STRING_COUNT 8

// Function hashes
#define ON_BIT0_RISE_HASH 0x13068D30
#define SE_LOG_HASH 0xCEBBEFA4
#define ON_BIT0_FALL_HASH 0xF8140330
#define ON_BITS_12_RISE_HASH 0xFE5ADA37
#define ON_BITS_12_FALL_HASH 0x7B832107
#define ON_BITS_34_RISE_HASH 0x6B533EF3
#define ON_BITS_34_FALL_HASH 0x29423823
#define ON_BIT5_CLEAR_HASH 0x15953A35
#define ON_BIT5_SET_HASH 0xAC23F0C8
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_TRIGGER_ON_CHANGE_HASH 0x8374277F
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_RETURN_CONTINUE_HASH 0xB4243714
#define TEST_BIT_HASH 0x2D749139
#define SE_PRED_AND_HASH 0x7C0DF5F3
#define SE_PRED_OR_HASH 0x0CF6212F
#define SE_PRED_NOT_HASH 0x217DEB8F

// Tree hashes
#define BASIC_PRIMITIVE_TEST_HASH 0xC0F76968

#ifdef __cplusplus
}
#endif

#endif // BASIC_PRIMITIVE_TEST_H
