// ============================================================================
// basic_primitive_test_debug.h
// Debug hash reference for basic_primitive_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef BASIC_PRIMITIVE_TEST_DEBUG_H
#define BASIC_PRIMITIVE_TEST_DEBUG_H

// Oneshot functions
#define H_13068D30 0x13068D30  // ON_BIT0_RISE
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_F8140330 0xF8140330  // ON_BIT0_FALL
#define H_FE5ADA37 0xFE5ADA37  // ON_BITS_12_RISE
#define H_7B832107 0x7B832107  // ON_BITS_12_FALL
#define H_6B533EF3 0x6B533EF3  // ON_BITS_34_RISE
#define H_29423823 0x29423823  // ON_BITS_34_FALL
#define H_15953A35 0x15953A35  // ON_BIT5_CLEAR
#define H_AC23F0C8 0xAC23F0C8  // ON_BIT5_SET

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_8374277F 0x8374277F  // SE_TRIGGER_ON_CHANGE
#define H_FFC1FAA4 0xFFC1FAA4  // SE_CHAIN_FLOW
#define H_B4243714 0xB4243714  // SE_RETURN_CONTINUE

// Predicate functions
#define H_2D749139 0x2D749139  // TEST_BIT
#define H_7C0DF5F3 0x7C0DF5F3  // SE_PRED_AND
#define H_0CF6212F 0x0CF6212F  // SE_PRED_OR
#define H_217DEB8F 0x217DEB8F  // SE_PRED_NOT

#endif // BASIC_PRIMITIVE_TEST_DEBUG_H
