// ============================================================================
// callback_function_dump_32.h
// DEBUG PARAMETER DUMP for callback_function
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef CALLBACK_FUNCTION_DUMP_32_H
#define CALLBACK_FUNCTION_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: callback_function
 * Hash:   0x0C1A5BFB
 * Trees:  1
 * Records: 1
 * Strings: 4
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0xF332B8D7 "callback test started"
 * [0x0001] (  1) hash=0xDB698917 "callback function called"
 * [0x0002] (  2) hash=0x8FB6B891 "do some stack work"
 * [0x0003] (  3) hash=0x55461F0E "call a dictionary function"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xCEBBEFA4 SE_LOG
 *   [0x0001] ( 1) hash=0x30DB52C3 SE_LOAD_FUNCTION
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0x4F4BB2E1 SE_SEQUENCE_ONCE
 *   [0x0002] ( 2) hash=0xC9C09EC0 SE_EXEC_FN
 *   [0x0003] ( 3) hash=0x0A5B8A85 SE_RETURN_FUNCTION_TERMINATE
 *
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: callback_function_blackboard (size=8, align=8, hash=0x590F5B8D)
 *   [ 0] off=0x0000 size= 8 hash=0xE4D06AB8 fn_ptr PTR64
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: callback_function
 *   hash=0x0C1A5BFB nodes=9 ptrs=1
 *   record=callback_function_blackboard (hash=0x590F5B8D)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]     32      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    3    ONESHOT   [0x08]      2      0  idx_to_ptr=0
 *    4      STR_IDX[0x0D]        0     21  "callback test started"
 *    5    CLOSE[0x06]          0      -  (end SE_LOG)
 *    6    OPEN_CALL[0x07]     18      0  SE_LOAD_FUNCTION hash=0x30DB52C3
 *    7    ONESHOT+SR[0x48]      6      1  idx_to_ptr=0
 *    8      FIELD[0x0B]          0      8  fn_ptr (off=0x0000, hash=0xE4D06AB8)
 *    9      OPEN_CALL[0x07]     14      0  SE_SEQUENCE_ONCE hash=0x4F4BB2E1
 *   10      MAIN      [0x09]      9      1  idx_to_ptr=0
 *   11        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   12        ONESHOT   [0x08]     11      0  idx_to_ptr=0
 *   13          STR_IDX[0x0D]        1     24  "callback function called"
 *   14        CLOSE[0x06]          0      -  (end SE_LOG)
 *   15        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   16        ONESHOT   [0x08]     15      0  idx_to_ptr=0
 *   17          STR_IDX[0x0D]        2     18  "do some stack work"
 *   18        CLOSE[0x06]          0      -  (end SE_LOG)
 *   19        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   20        ONESHOT   [0x08]     19      0  idx_to_ptr=0
 *   21          STR_IDX[0x0D]        3     26  "call a dictionary function"
 *   22        CLOSE[0x06]          0      -  (end SE_LOG)
 *   23      CLOSE[0x06]          0      -  (end SE_SEQUENCE_ONCE)
 *   24    CLOSE[0x06]          0      -  (end SE_LOAD_FUNCTION)
 *   25    OPEN_CALL[0x07]      3      0  SE_EXEC_FN hash=0xC9C09EC0
 *   26    MAIN+PTR  [0x89]     25      2  idx_to_ptr=0
 *   27      FIELD[0x0B]          0      8  fn_ptr (off=0x0000, hash=0xE4D06AB8)
 *   28    CLOSE[0x06]          0      -  (end SE_EXEC_FN)
 *   29    OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_TERMINATE hash=0x0A5B8A85
 *   30    MAIN      [0x09]     29      3  idx_to_ptr=0
 *   31    CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_TERMINATE)
 *   32  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 33
 */

#endif // CALLBACK_FUNCTION_DUMP_32_H
