// ============================================================================
// callback_function.h
// Generated S-expression module for callback_function
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef CALLBACK_FUNCTION_H
#define CALLBACK_FUNCTION_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "callback_function_records.h"

// Module: callback_function
#define CALLBACK_FUNCTION_NAME_HASH 0x0C1A5BFB
#define CALLBACK_FUNCTION_TREE_COUNT 1
#define CALLBACK_FUNCTION_RECORD_COUNT 1

// String table
static const char* const callback_function_strings[] = {
    "callback test started",
    "callback function called",
    "do some stack work",
    "call a dictionary function"
};
#define CALLBACK_FUNCTION_STRING_COUNT 4

// Function hashes
#define SE_LOG_HASH 0xCEBBEFA4
#define SE_LOAD_FUNCTION_HASH 0x30DB52C3
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_SEQUENCE_ONCE_HASH 0x4F4BB2E1
#define SE_EXEC_FN_HASH 0xC9C09EC0
#define SE_RETURN_FUNCTION_TERMINATE_HASH 0x0A5B8A85

// Tree hashes
#define CALLBACK_FUNCTION_HASH 0x0C1A5BFB

// Record hashes
#define CALLBACK_FUNCTION_BLACKBOARD_HASH 0x590F5B8D

// Field hashes
#define FIELD_FN_PTR_HASH 0xE4D06AB8

#ifdef __cplusplus
}
#endif

#endif // CALLBACK_FUNCTION_H
