// ============================================================================
// callback_function_module_rom.c
// Generated S-expression module for callback_function (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "callback_function_records.h"
#include "callback_function.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.

static const s_expr_field_desc_t callback_function_callback_function_blackboard_fields[] = {
    { .name_hash = 0xE4D06AB8U, .offset = 0, .size = 8 }
};

static const s_expr_record_desc_t callback_function_records[] = {
    { .name_hash = 0x590F5B8DU, .total_size = 8, .field_count = 1, .fields = callback_function_callback_function_blackboard_fields }
};

// Tree: callback_function (params=33, nodes=9)
static const s_expr_param_t callback_function_callback_function_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 21 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 18, .parent_offset = 5 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 2, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 24 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 26 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 16 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 18, .parent_offset = 23 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 24 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 7, .func_index = 2 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 27 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 28 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 8, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t callback_function_trees[] = {
    {
        .name_hash = 0x0C1A5BFBU,
        .record_hash = 0x590F5B8DU,
        .params = callback_function_callback_function_params,
        .param_count = 33,
        .func_node_count = 9,
        .pointer_count = 1,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t callback_function_oneshot_fns[] = {
    se_log,  // 0: SE_LOG
    se_load_function  // 1: SE_LOAD_FUNCTION
};

static const s_expr_main_fn_t callback_function_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    se_sequence_once,  // 1: SE_SEQUENCE_ONCE
    se_exec_fn,  // 2: SE_EXEC_FN
    se_return_function_terminate  // 3: SE_RETURN_FUNCTION_TERMINATE
};

static const s_expr_pred_fn_t callback_function_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t callback_function_module_rom = {
    .name_hash = 0x0C1A5BFBU,
    .is_64bit = false,
    .trees = callback_function_trees,
    .tree_count = 1,
    .records = callback_function_records,
    .record_count = 1,
    .string_table = callback_function_strings,
    .string_count = 4,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = callback_function_oneshot_fns,
    .oneshot_count = 2,
    .main_fns = callback_function_main_fns,
    .main_count = 4,
    .pred_fns = callback_function_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 9,
    .max_pointer_count = 1,
    .max_param_count = 33,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

