// ============================================================================
// callback_function_records.h
// Generated record structures for callback_function
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef CALLBACK_FUNCTION_RECORDS_H
#define CALLBACK_FUNCTION_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct callback_function_blackboard_s callback_function_blackboard_t;

// Record: callback_function_blackboard (size=8, align=8)
struct callback_function_blackboard_s {
    uint64_t fn_ptr;  // offset=0, size=8 (ptr64)
};

#endif // CALLBACK_FUNCTION_RECORDS_H
