// ============================================================================
// callback_function_debug.h
// Debug hash reference for callback_function
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef CALLBACK_FUNCTION_DEBUG_H
#define CALLBACK_FUNCTION_DEBUG_H

// Oneshot functions
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_30DB52C3 0x30DB52C3  // SE_LOAD_FUNCTION

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_4F4BB2E1 0x4F4BB2E1  // SE_SEQUENCE_ONCE
#define H_C9C09EC0 0xC9C09EC0  // SE_EXEC_FN
#define H_0A5B8A85 0x0A5B8A85  // SE_RETURN_FUNCTION_TERMINATE

#endif // CALLBACK_FUNCTION_DEBUG_H
