// ============================================================================
// callback_function_user_functions.h
// User function prototypes for callback_function
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef CALLBACK_FUNCTION_USER_FUNCTIONS_H
#define CALLBACK_FUNCTION_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif // CALLBACK_FUNCTION_USER_FUNCTIONS_H
