// ============================================================================
// state_machine_test_module_rom.c
// Generated S-expression module for state_machine_test (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "state_machine_test_records.h"
#include "state_machine_test.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern void cfl_disable_children(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void cfl_enable_child(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

static const s_expr_field_desc_t state_machine_test_state_machine_blackboard_fields[] = {
    { .name_hash = 0x783132F6U, .offset = 0, .size = 4 }
};

static const s_expr_record_desc_t state_machine_test_records[] = {
    { .name_hash = 0xC89D038CU, .total_size = 4, .field_count = 1, .fields = state_machine_test_state_machine_blackboard_fields }
};

// Tree: state_machine_test (params=183, nodes=48)
static const s_expr_param_t state_machine_test_state_machine_test_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 182, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 5 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 2, .func_index = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 4, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 25 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 19 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 20 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 6, .func_index = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 7, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 1, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 9, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 10, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 14, .parent_offset = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 37 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 38 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 11, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 42 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 43 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 12, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 4, .str_len = 26 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 46 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 122, .parent_offset = 47 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 13, .func_index = 5 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 3 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 14, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 15, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 5, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 2, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x89, .index_to_pointer = 2, .node_index = 18, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 20 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 21 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 20, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 6, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 25 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 21, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 32 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 34 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 22, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 23, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 7, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 24, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 25, .func_index = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 3, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x89, .index_to_pointer = 3, .node_index = 26, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 27, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 2U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 20 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 21 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 28, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 8, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 25 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 29, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 63 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 65 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 30, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 31, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 9, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 32, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 33, .func_index = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 4, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x89, .index_to_pointer = 4, .node_index = 34, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 10 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 35, .func_index = 1 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 20 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 21 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 36, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 10, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 25 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 37, .func_index = 6 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 29, .parent_offset = 94 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 24, .parent_offset = 96 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 38, .func_index = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 39, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 9, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 40, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 41, .func_index = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 5, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x89, .index_to_pointer = 5, .node_index = 42, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 100 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 43, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 10, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 19 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 20 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 44, .func_index = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 22 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 24, .parent_offset = 120 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 122, .parent_offset = 169 },
    { .type = 0x07, .index_to_pointer = 6, .brace_idx = 3, .parent_offset = 170 },
    { .type = 0x89, .index_to_pointer = 6, .node_index = 45, .func_index = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 350 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 173 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 174 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 46, .func_index = 0 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 11, .str_len = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 177 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 178 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 47, .func_index = 8 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 180 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 182, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t state_machine_test_trees[] = {
    {
        .name_hash = 0x6824A885U,
        .record_hash = 0xC89D038CU,
        .params = state_machine_test_state_machine_test_params,
        .param_count = 183,
        .func_node_count = 48,
        .pointer_count = 7,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t state_machine_test_oneshot_fns[] = {
    se_log,  // 0: SE_LOG
    se_set_field,  // 1: SE_SET_FIELD
    cfl_disable_children,  // 2: CFL_DISABLE_CHILDREN
    cfl_enable_child  // 3: CFL_ENABLE_CHILD
};

static const s_expr_main_fn_t state_machine_test_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    se_fork_join,  // 1: SE_FORK_JOIN
    se_tick_delay,  // 2: SE_TICK_DELAY
    se_fork,  // 3: SE_FORK
    se_sequence,  // 4: SE_SEQUENCE
    se_state_machine,  // 5: SE_STATE_MACHINE
    se_return_pipeline_disable,  // 6: SE_RETURN_PIPELINE_DISABLE
    se_return_terminate,  // 7: SE_RETURN_TERMINATE
    se_return_function_terminate  // 8: SE_RETURN_FUNCTION_TERMINATE
};

static const s_expr_pred_fn_t state_machine_test_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t state_machine_test_module_rom = {
    .name_hash = 0x6824A885U,
    .is_64bit = false,
    .trees = state_machine_test_trees,
    .tree_count = 1,
    .records = state_machine_test_records,
    .record_count = 1,
    .string_table = state_machine_test_strings,
    .string_count = 12,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = state_machine_test_oneshot_fns,
    .oneshot_count = 4,
    .main_fns = state_machine_test_main_fns,
    .main_count = 9,
    .pred_fns = state_machine_test_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 48,
    .max_pointer_count = 7,
    .max_param_count = 183,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

