// ============================================================================
// state_machine_test_user_functions.h
// User function prototypes for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef STATE_MACHINE_TEST_USER_FUNCTIONS_H
#define STATE_MACHINE_TEST_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// Oneshot functions
void cfl_disable_children(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

void cfl_enable_child(
    s_expr_tree_instance_t* inst,
    const s_expr_param_t* params,
    uint16_t param_count,
    s_expr_event_type_t event_type,
    uint16_t event_id,
    void* event_data
);

#ifdef __cplusplus
}
#endif

#endif // STATE_MACHINE_TEST_USER_FUNCTIONS_H
