// ============================================================================
// state_machine_test_debug.h
// Debug hash reference for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef STATE_MACHINE_TEST_DEBUG_H
#define STATE_MACHINE_TEST_DEBUG_H

// Oneshot functions
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_FFF84A15 0xFFF84A15  // SE_SET_FIELD
#define H_5839B05B 0x5839B05B  // CFL_DISABLE_CHILDREN
#define H_D42E3453 0xD42E3453  // CFL_ENABLE_CHILD

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_E404E1CF 0xE404E1CF  // SE_FORK_JOIN
#define H_0C3460EB 0x0C3460EB  // SE_TICK_DELAY
#define H_0A24332A 0x0A24332A  // SE_FORK
#define H_EC3EE7BF 0xEC3EE7BF  // SE_SEQUENCE
#define H_5EEDA8E9 0x5EEDA8E9  // SE_STATE_MACHINE
#define H_6B7AA500 0x6B7AA500  // SE_RETURN_PIPELINE_DISABLE
#define H_DFE64C74 0xDFE64C74  // SE_RETURN_TERMINATE
#define H_0A5B8A85 0x0A5B8A85  // SE_RETURN_FUNCTION_TERMINATE

#endif // STATE_MACHINE_TEST_DEBUG_H
