// ============================================================================
// state_machine_test_records.h
// Generated record structures for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef STATE_MACHINE_TEST_RECORDS_H
#define STATE_MACHINE_TEST_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct state_machine_blackboard_s state_machine_blackboard_t;

// Record: state_machine_blackboard (size=4, align=4)
struct state_machine_blackboard_s {
    int32_t state;  // offset=0, size=4
};

#endif // STATE_MACHINE_TEST_RECORDS_H
