// ============================================================================
// state_machine_test_user_registration.c
// User function registration for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "state_machine_test.h"
#include "state_machine_test_user_functions.h"
#include "s_engine_module.h"

// Oneshot function entries
static s_expr_fn_entry_t state_machine_test_oneshot_entries[] = {
    { 0x5839B05B, (void*)cfl_disable_children },
    { 0xD42E3453, (void*)cfl_enable_child },
};

static const s_expr_fn_table_t state_machine_test_oneshot_table = {
    .entries = state_machine_test_oneshot_entries,
    .count = 2
};

// Table accessors
const s_expr_fn_table_t* state_machine_test_get_oneshot_table(void) {
    return &state_machine_test_oneshot_table;
}

const s_expr_fn_table_t* state_machine_test_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* state_machine_test_get_pred_table(void) {
    return NULL;
}

// Register all user functions with module
void state_machine_test_register_all(s_expr_module_t* module) {
    s_expr_module_register_oneshot(module, &state_machine_test_oneshot_table);
}
