// ============================================================================
// state_machine_test_dump_32.h
// DEBUG PARAMETER DUMP for state_machine_test
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef STATE_MACHINE_TEST_DUMP_32_H
#define STATE_MACHINE_TEST_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: state_machine_test
 * Hash:   0x6824A885
 * Trees:  1
 * Records: 1
 * Strings: 12
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0xB5554AF8 "Fork Join Test Started"
 * [0x0001] (  1) hash=0x92683676 "Fork Join Test Terminated"
 * [0x0002] (  2) hash=0x89771B37 "Fork 1 Test Started"
 * [0x0003] (  3) hash=0x347BAC9F "Fork 1 Test Terminated"
 * [0x0004] (  4) hash=0x7C533240 "State machine test started"
 * [0x0005] (  5) hash=0x89FA9636 "State 0"
 * [0x0006] (  6) hash=0xA45143A3 "State 0 terminated"
 * [0x0007] (  7) hash=0x8AFA97C9 "State 1"
 * [0x0008] (  8) hash=0x0090A1DE "State 1 terminated"
 * [0x0009] (  9) hash=0x87FA9310 "State 2"
 * [0x000A] ( 10) hash=0x8300AF51 "State 2 terminated"
 * [0x000B] ( 11) hash=0x86413765 "State machine test finished"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xCEBBEFA4 SE_LOG
 *   [0x0001] ( 1) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0002] ( 2) hash=0x5839B05B CFL_DISABLE_CHILDREN
 *   [0x0003] ( 3) hash=0xD42E3453 CFL_ENABLE_CHILD
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0xE404E1CF SE_FORK_JOIN
 *   [0x0002] ( 2) hash=0x0C3460EB SE_TICK_DELAY
 *   [0x0003] ( 3) hash=0x0A24332A SE_FORK
 *   [0x0004] ( 4) hash=0xEC3EE7BF SE_SEQUENCE
 *   [0x0005] ( 5) hash=0x5EEDA8E9 SE_STATE_MACHINE
 *   [0x0006] ( 6) hash=0x6B7AA500 SE_RETURN_PIPELINE_DISABLE
 *   [0x0007] ( 7) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *   [0x0008] ( 8) hash=0x0A5B8A85 SE_RETURN_FUNCTION_TERMINATE
 *
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: state_machine_blackboard (size=4, align=4, hash=0xC89D038C)
 *   [ 0] off=0x0000 size= 4 hash=0x783132F6 state
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: state_machine_test
 *   hash=0x6824A885 nodes=48 ptrs=7
 *   record=state_machine_blackboard (hash=0xC89D038C)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    182      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    3    ONESHOT   [0x08]      2      0  idx_to_ptr=0
 *    4      STR_IDX[0x0D]        0     22  "Fork Join Test Started"
 *    5    CLOSE[0x06]          0      -  (end SE_LOG)
 *    6    OPEN_CALL[0x07]     14      0  SE_FORK_JOIN hash=0xE404E1CF
 *    7    MAIN      [0x09]      6      1  idx_to_ptr=0
 *    8      OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    9      ONESHOT   [0x08]      8      0  idx_to_ptr=0
 *   10        STR_IDX[0x0D]        0     22  "Fork Join Test Started"
 *   11      CLOSE[0x06]          0      -  (end SE_LOG)
 *   12      OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   13      MAIN+PTR  [0x89]     12      2  idx_to_ptr=0
 *   14        INT[0x00]            -      -  10 (0x0000000A)
 *   15      CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *   16      OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   17      ONESHOT   [0x08]     16      0  idx_to_ptr=0
 *   18        STR_IDX[0x0D]        1     25  "Fork Join Test Terminated"
 *   19      CLOSE[0x06]          0      -  (end SE_LOG)
 *   20    CLOSE[0x06]          0      -  (end SE_FORK_JOIN)
 *   21    OPEN_CALL[0x07]     17      0  SE_FORK hash=0x0A24332A
 *   22    MAIN      [0x09]     21      3  idx_to_ptr=0
 *   23      OPEN_CALL[0x07]     14      0  SE_SEQUENCE hash=0xEC3EE7BF
 *   24      MAIN      [0x09]     23      4  idx_to_ptr=0
 *   25        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   26        ONESHOT   [0x08]     25      0  idx_to_ptr=0
 *   27          STR_IDX[0x0D]        2     19  "Fork 1 Test Started"
 *   28        CLOSE[0x06]          0      -  (end SE_LOG)
 *   29        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   30        MAIN+PTR  [0x89]     29      2  idx_to_ptr=1
 *   31          INT[0x00]            -      -  10 (0x0000000A)
 *   32        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *   33        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   34        ONESHOT   [0x08]     33      0  idx_to_ptr=0
 *   35          STR_IDX[0x0D]        3     22  "Fork 1 Test Terminated"
 *   36        CLOSE[0x06]          0      -  (end SE_LOG)
 *   37      CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *   38    CLOSE[0x06]          0      -  (end SE_FORK)
 *   39    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   40    ONESHOT+SR[0x48]     39      1  idx_to_ptr=0
 *   41      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   42      UINT[0x01]           -      -  0 (0x00000000)
 *   43    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   44    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   45    ONESHOT   [0x08]     44      0  idx_to_ptr=0
 *   46      STR_IDX[0x0D]        4     26  "State machine test started"
 *   47    CLOSE[0x06]          0      -  (end SE_LOG)
 *   48    OPEN_CALL[0x07]    122      0  SE_STATE_MACHINE hash=0x5EEDA8E9
 *   49    MAIN      [0x09]     48      5  idx_to_ptr=0
 *   50      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   51      INT[0x00]            -      -  0 (0x00000000)
 *   52      OPEN_CALL[0x07]     29      0  SE_SEQUENCE hash=0xEC3EE7BF
 *   53      MAIN      [0x09]     52      4  idx_to_ptr=0
 *   54        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   55        ONESHOT   [0x08]     54      0  idx_to_ptr=0
 *   56          STR_IDX[0x0D]        5      7  "State 0"
 *   57        CLOSE[0x06]          0      -  (end SE_LOG)
 *   58        OPEN_CALL[0x07]      2      0  CFL_DISABLE_CHILDREN hash=0x5839B05B
 *   59        ONESHOT   [0x08]     58      2  idx_to_ptr=0
 *   60        CLOSE[0x06]          0      -  (end CFL_DISABLE_CHILDREN)
 *   61        OPEN_CALL[0x07]      3      0  CFL_ENABLE_CHILD hash=0xD42E3453
 *   62        ONESHOT   [0x08]     61      3  idx_to_ptr=0
 *   63          INT[0x00]            -      -  0 (0x00000000)
 *   64        CLOSE[0x06]          0      -  (end CFL_ENABLE_CHILD)
 *   65        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   66        MAIN+PTR  [0x89]     65      2  idx_to_ptr=2
 *   67          INT[0x00]            -      -  10 (0x0000000A)
 *   68        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *   69        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   70        ONESHOT   [0x08]     69      1  idx_to_ptr=0
 *   71          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   72          UINT[0x01]           -      -  1 (0x00000001)
 *   73        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   74        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   75        ONESHOT   [0x08]     74      0  idx_to_ptr=0
 *   76          STR_IDX[0x0D]        6     18  "State 0 terminated"
 *   77        CLOSE[0x06]          0      -  (end SE_LOG)
 *   78        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *   79        MAIN      [0x09]     78      6  idx_to_ptr=0
 *   80        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *   81      CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *   82      INT[0x00]            -      -  1 (0x00000001)
 *   83      OPEN_CALL[0x07]     29      0  SE_SEQUENCE hash=0xEC3EE7BF
 *   84      MAIN      [0x09]     83      4  idx_to_ptr=0
 *   85        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   86        ONESHOT   [0x08]     85      0  idx_to_ptr=0
 *   87          STR_IDX[0x0D]        7      7  "State 1"
 *   88        CLOSE[0x06]          0      -  (end SE_LOG)
 *   89        OPEN_CALL[0x07]      2      0  CFL_DISABLE_CHILDREN hash=0x5839B05B
 *   90        ONESHOT   [0x08]     89      2  idx_to_ptr=0
 *   91        CLOSE[0x06]          0      -  (end CFL_DISABLE_CHILDREN)
 *   92        OPEN_CALL[0x07]      3      0  CFL_ENABLE_CHILD hash=0xD42E3453
 *   93        ONESHOT   [0x08]     92      3  idx_to_ptr=0
 *   94          INT[0x00]            -      -  1 (0x00000001)
 *   95        CLOSE[0x06]          0      -  (end CFL_ENABLE_CHILD)
 *   96        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *   97        MAIN+PTR  [0x89]     96      2  idx_to_ptr=3
 *   98          INT[0x00]            -      -  10 (0x0000000A)
 *   99        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  100        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  101        ONESHOT   [0x08]    100      1  idx_to_ptr=0
 *  102          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *  103          UINT[0x01]           -      -  2 (0x00000002)
 *  104        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  105        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  106        ONESHOT   [0x08]    105      0  idx_to_ptr=0
 *  107          STR_IDX[0x0D]        8     18  "State 1 terminated"
 *  108        CLOSE[0x06]          0      -  (end SE_LOG)
 *  109        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *  110        MAIN      [0x09]    109      6  idx_to_ptr=0
 *  111        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *  112      CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  113      INT[0x00]            -      -  2 (0x00000002)
 *  114      OPEN_CALL[0x07]     29      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  115      MAIN      [0x09]    114      4  idx_to_ptr=0
 *  116        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  117        ONESHOT   [0x08]    116      0  idx_to_ptr=0
 *  118          STR_IDX[0x0D]        9      7  "State 2"
 *  119        CLOSE[0x06]          0      -  (end SE_LOG)
 *  120        OPEN_CALL[0x07]      2      0  CFL_DISABLE_CHILDREN hash=0x5839B05B
 *  121        ONESHOT   [0x08]    120      2  idx_to_ptr=0
 *  122        CLOSE[0x06]          0      -  (end CFL_DISABLE_CHILDREN)
 *  123        OPEN_CALL[0x07]      3      0  CFL_ENABLE_CHILD hash=0xD42E3453
 *  124        ONESHOT   [0x08]    123      3  idx_to_ptr=0
 *  125          INT[0x00]            -      -  2 (0x00000002)
 *  126        CLOSE[0x06]          0      -  (end CFL_ENABLE_CHILD)
 *  127        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  128        MAIN+PTR  [0x89]    127      2  idx_to_ptr=4
 *  129          INT[0x00]            -      -  10 (0x0000000A)
 *  130        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  131        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  132        ONESHOT   [0x08]    131      1  idx_to_ptr=0
 *  133          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *  134          UINT[0x01]           -      -  0 (0x00000000)
 *  135        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  136        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  137        ONESHOT   [0x08]    136      0  idx_to_ptr=0
 *  138          STR_IDX[0x0D]       10     18  "State 2 terminated"
 *  139        CLOSE[0x06]          0      -  (end SE_LOG)
 *  140        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *  141        MAIN      [0x09]    140      6  idx_to_ptr=0
 *  142        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *  143      CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  144      INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *  145      OPEN_CALL[0x07]     24      0  SE_SEQUENCE hash=0xEC3EE7BF
 *  146      MAIN      [0x09]    145      4  idx_to_ptr=0
 *  147        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  148        ONESHOT   [0x08]    147      0  idx_to_ptr=0
 *  149          STR_IDX[0x0D]        9      7  "State 2"
 *  150        CLOSE[0x06]          0      -  (end SE_LOG)
 *  151        OPEN_CALL[0x07]      2      0  CFL_DISABLE_CHILDREN hash=0x5839B05B
 *  152        ONESHOT   [0x08]    151      2  idx_to_ptr=0
 *  153        CLOSE[0x06]          0      -  (end CFL_DISABLE_CHILDREN)
 *  154        OPEN_CALL[0x07]      3      0  CFL_ENABLE_CHILD hash=0xD42E3453
 *  155        ONESHOT   [0x08]    154      3  idx_to_ptr=0
 *  156          INT[0x00]            -      -  2 (0x00000002)
 *  157        CLOSE[0x06]          0      -  (end CFL_ENABLE_CHILD)
 *  158        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  159        MAIN+PTR  [0x89]    158      2  idx_to_ptr=5
 *  160          INT[0x00]            -      -  100 (0x00000064)
 *  161        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  162        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  163        ONESHOT   [0x08]    162      0  idx_to_ptr=0
 *  164          STR_IDX[0x0D]       10     18  "State 2 terminated"
 *  165        CLOSE[0x06]          0      -  (end SE_LOG)
 *  166        OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  167        MAIN      [0x09]    166      7  idx_to_ptr=0
 *  168        CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  169      CLOSE[0x06]          0      -  (end SE_SEQUENCE)
 *  170    CLOSE[0x06]          0      -  (end SE_STATE_MACHINE)
 *  171    OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  172    MAIN+PTR  [0x89]    171      2  idx_to_ptr=6
 *  173      INT[0x00]            -      -  350 (0x0000015E)
 *  174    CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  175    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  176    ONESHOT   [0x08]    175      0  idx_to_ptr=0
 *  177      STR_IDX[0x0D]       11     27  "State machine test finished"
 *  178    CLOSE[0x06]          0      -  (end SE_LOG)
 *  179    OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_TERMINATE hash=0x0A5B8A85
 *  180    MAIN      [0x09]    179      8  idx_to_ptr=0
 *  181    CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_TERMINATE)
 *  182  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 183
 */

#endif // STATE_MACHINE_TEST_DUMP_32_H
