// ============================================================================
// state_machine_test.h
// Generated S-expression module for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef STATE_MACHINE_TEST_H
#define STATE_MACHINE_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "state_machine_test_records.h"

// Module: state_machine_test
#define STATE_MACHINE_TEST_NAME_HASH 0x6824A885
#define STATE_MACHINE_TEST_TREE_COUNT 1
#define STATE_MACHINE_TEST_RECORD_COUNT 1

// String table
static const char* const state_machine_test_strings[] = {
    "Fork Join Test Started",
    "Fork Join Test Terminated",
    "Fork 1 Test Started",
    "Fork 1 Test Terminated",
    "State machine test started",
    "State 0",
    "State 0 terminated",
    "State 1",
    "State 1 terminated",
    "State 2",
    "State 2 terminated",
    "State machine test finished"
};
#define STATE_MACHINE_TEST_STRING_COUNT 12

// Function hashes
#define SE_LOG_HASH 0xCEBBEFA4
#define SE_SET_FIELD_HASH 0xFFF84A15
#define CFL_DISABLE_CHILDREN_HASH 0x5839B05B
#define CFL_ENABLE_CHILD_HASH 0xD42E3453
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_FORK_JOIN_HASH 0xE404E1CF
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_FORK_HASH 0x0A24332A
#define SE_SEQUENCE_HASH 0xEC3EE7BF
#define SE_STATE_MACHINE_HASH 0x5EEDA8E9
#define SE_RETURN_PIPELINE_DISABLE_HASH 0x6B7AA500
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74
#define SE_RETURN_FUNCTION_TERMINATE_HASH 0x0A5B8A85

// Tree hashes
#define STATE_MACHINE_TEST_HASH 0x6824A885

// Record hashes
#define STATE_MACHINE_BLACKBOARD_HASH 0xC89D038C

// Field hashes
#define FIELD_STATE_HASH 0x783132F6

#ifdef __cplusplus
}
#endif

#endif // STATE_MACHINE_TEST_H
