// ============================================================================
// register_dongle.h
// Generated S-expression module for register_dongle
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef REGISTER_DONGLE_H
#define REGISTER_DONGLE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"

// Module: register_dongle
#define REGISTER_DONGLE_NAME_HASH 0xBAEA04D8
#define REGISTER_DONGLE_TREE_COUNT 1
#define REGISTER_DONGLE_RECORD_COUNT 0

// Function hashes
#define SEND_REGISTER_HASH 0xD9617BB9
#define SEND_HEARTBEAT_HASH 0x161B5180
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_FORK_HASH 0x0A24332A
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_RETURN_PIPELINE_RESET_HASH 0x8CD80263
#define TOGGLE_LED_HASH 0xD47C91E7
#define SE_RETURN_HALT_HASH 0x056FB9EA

// Tree hashes
#define REGISTER_DONGLE_HASH 0xBAEA04D8

#ifdef __cplusplus
}
#endif

#endif // REGISTER_DONGLE_H
