// ============================================================================
// register_dongle_v2.h
// Generated S-expression module for register_dongle_v2
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef REGISTER_DONGLE_V2_H
#define REGISTER_DONGLE_V2_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "register_dongle_v2_records.h"

// Module: register_dongle_v2
#define REGISTER_DONGLE_V2_NAME_HASH 0xAE14A061
#define REGISTER_DONGLE_V2_TREE_COUNT 1
#define REGISTER_DONGLE_V2_RECORD_COUNT 1

// String table
static const char* const register_dongle_v2_strings[] = {
    "BOOT: received OP_REGISTER_ACK -> OPERATIONAL",
    "FATAL: unknown dongle_state"
};
#define REGISTER_DONGLE_V2_STRING_COUNT 2

// Function hashes
#define SEND_REGISTER_HASH 0xD9617BB9
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_HASH 0xCEBBEFA4
#define SEND_HEARTBEAT_HASH 0x161B5180
#define SEND_PONG_HASH 0x2E51CF2A
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_STATE_MACHINE_HASH 0x5EEDA8E9
#define SE_EVENT_DISPATCH_HASH 0xF3EDFC75
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_RETURN_PIPELINE_RESET_HASH 0x8CD80263
#define SE_RETURN_PIPELINE_HALT_HASH 0x4AC84487
#define SE_FORK_HASH 0x0A24332A
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define TOGGLE_LED_HASH 0xD47C91E7
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74
#define SE_RETURN_HALT_HASH 0x056FB9EA

// Tree hashes
#define REGISTER_DONGLE_V2_HASH 0xAE14A061

// Record hashes
#define DONGLE_RECORD_HASH 0x84FEA724

// Field hashes
#define FIELD_DONGLE_STATE_HASH 0x57075F2E

#ifdef __cplusplus
}
#endif

#endif // REGISTER_DONGLE_V2_H
