// ============================================================================
// return_tests_user_functions.h
// User function prototypes for return_tests
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// ============================================================================

#ifndef RETURN_TESTS_USER_FUNCTIONS_H
#define RETURN_TESTS_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif // RETURN_TESTS_USER_FUNCTIONS_H
