// ============================================================================
// return_tests_dump_32.h
// DEBUG PARAMETER DUMP for return_tests
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef RETURN_TESTS_DUMP_32_H
#define RETURN_TESTS_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: return_tests
 * Hash:   0xAF90FF75
 * Trees:  18
 * Records: 0
 * Strings: 0
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xB4243714 SE_RETURN_CONTINUE
 *   [0x0001] ( 1) hash=0x056FB9EA SE_RETURN_HALT
 *   [0x0002] ( 2) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *   [0x0003] ( 3) hash=0x70EAA030 SE_RETURN_RESET
 *   [0x0004] ( 4) hash=0x02C11A13 SE_RETURN_DISABLE
 *   [0x0005] ( 5) hash=0xEAE5524E SE_RETURN_SKIP_CONTINUE
 *   [0x0006] ( 6) hash=0xF7191B5B SE_RETURN_FUNCTION_CONTINUE
 *   [0x0007] ( 7) hash=0x891F0675 SE_RETURN_FUNCTION_HALT
 *   [0x0008] ( 8) hash=0x0A5B8A85 SE_RETURN_FUNCTION_TERMINATE
 *   [0x0009] ( 9) hash=0xF6027E85 SE_RETURN_FUNCTION_RESET
 *   [0x000A] (10) hash=0x7E3D3A4A SE_RETURN_FUNCTION_DISABLE
 *   [0x000B] (11) hash=0x338AC3DB SE_RETURN_FUNCTION_SKIP_CONTINUE
 *   [0x000C] (12) hash=0x5A902F85 SE_RETURN_PIPELINE_CONTINUE
 *   [0x000D] (13) hash=0x4AC84487 SE_RETURN_PIPELINE_HALT
 *   [0x000E] (14) hash=0x0933AC9B SE_RETURN_PIPELINE_TERMINATE
 *   [0x000F] (15) hash=0x8CD80263 SE_RETURN_PIPELINE_RESET
 *   [0x0010] (16) hash=0x6B7AA500 SE_RETURN_PIPELINE_DISABLE
 *   [0x0011] (17) hash=0xD3A0766D SE_RETURN_PIPELINE_SKIP_CONTINUE
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: return_continue_test
 *   hash=0x5BEA640A nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_CONTINUE hash=0xB4243714
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_CONTINUE)
 *
 * Total params: 3
 */

/*
 * TREE: return_halt_test
 *   hash=0x99EFDDC0 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_HALT hash=0x056FB9EA
 *    1  MAIN      [0x09]      0      1  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_HALT)
 *
 * Total params: 3
 */

/*
 * TREE: return_terminate_test
 *   hash=0x0F3DCDA4 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *    1  MAIN      [0x09]      0      2  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *
 * Total params: 3
 */

/*
 * TREE: return_reset_test
 *   hash=0xC20F4504 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_RESET hash=0x70EAA030
 *    1  MAIN      [0x09]      0      3  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_RESET)
 *
 * Total params: 3
 */

/*
 * TREE: return_disable_test
 *   hash=0x381457B1 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_DISABLE hash=0x02C11A13
 *    1  MAIN      [0x09]      0      4  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_DISABLE)
 *
 * Total params: 3
 */

/*
 * TREE: return_skip_continue_test
 *   hash=0xA58DA842 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_SKIP_CONTINUE hash=0xEAE5524E
 *    1  MAIN      [0x09]      0      5  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_SKIP_CONTINUE)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_continue_test
 *   hash=0x92D5E4E9 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_CONTINUE hash=0xF7191B5B
 *    1  MAIN      [0x09]      0      6  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_CONTINUE)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_halt_test
 *   hash=0x1D7C493B nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_HALT hash=0x891F0675
 *    1  MAIN      [0x09]      0      7  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_HALT)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_terminate_test
 *   hash=0x1B509D29 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_TERMINATE hash=0x0A5B8A85
 *    1  MAIN      [0x09]      0      8  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_TERMINATE)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_reset_test
 *   hash=0xA4CD827D nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_RESET hash=0xF6027E85
 *    1  MAIN      [0x09]      0      9  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_RESET)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_disable_test
 *   hash=0x275F0EE0 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_DISABLE hash=0x7E3D3A4A
 *    1  MAIN      [0x09]      0     10  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_DISABLE)
 *
 * Total params: 3
 */

/*
 * TREE: return_function_skip_continue_test
 *   hash=0x09EC0E57 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_FUNCTION_SKIP_CONTINUE hash=0x338AC3DB
 *    1  MAIN      [0x09]      0     11  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_FUNCTION_SKIP_CONTINUE)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_continue_test
 *   hash=0x50222FFB nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_CONTINUE hash=0x5A902F85
 *    1  MAIN      [0x09]      0     12  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_CONTINUE)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_halt_test
 *   hash=0xEB5C011D nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_HALT hash=0x4AC84487
 *    1  MAIN      [0x09]      0     13  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_HALT)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_terminate_test
 *   hash=0x824A77DF nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_TERMINATE hash=0x0933AC9B
 *    1  MAIN      [0x09]      0     14  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_TERMINATE)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_reset_test
 *   hash=0x338090A3 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *    1  MAIN      [0x09]      0     15  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_disable_test
 *   hash=0x2D614786 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_DISABLE hash=0x6B7AA500
 *    1  MAIN      [0x09]      0     16  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_DISABLE)
 *
 * Total params: 3
 */

/*
 * TREE: return_pipeline_skip_continue_test
 *   hash=0x3A917129 nodes=1 ptrs=0
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_SKIP_CONTINUE hash=0xD3A0766D
 *    1  MAIN      [0x09]      0     17  idx_to_ptr=0
 *    2  CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_SKIP_CONTINUE)
 *
 * Total params: 3
 */

#endif // RETURN_TESTS_DUMP_32_H
