// ============================================================================
// return_tests_user_registration.c
// User function registration for return_tests
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "return_tests.h"
#include "return_tests_user_functions.h"
#include "s_engine_module.h"

// Table accessors
const s_expr_fn_table_t* return_tests_get_oneshot_table(void) {
    return NULL;
}

const s_expr_fn_table_t* return_tests_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* return_tests_get_pred_table(void) {
    return NULL;
}

// Register all user functions with module
void return_tests_register_all(s_expr_module_t* module) {
}
