// ============================================================================
// advanced_primitive_test_records.h
// Generated record structures for advanced_primitive_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef ADVANCED_PRIMITIVE_TEST_RECORDS_H
#define ADVANCED_PRIMITIVE_TEST_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct state_machine_blackboard_s state_machine_blackboard_t;

// Record: state_machine_blackboard (size=20, align=4)
struct state_machine_blackboard_s {
    int32_t state;  // offset=0, size=4
    float event_data_1;  // offset=4, size=4
    float event_data_2;  // offset=8, size=4
    float event_data_3;  // offset=12, size=4
    float event_data_4;  // offset=16, size=4
};

#endif // ADVANCED_PRIMITIVE_TEST_RECORDS_H
