// ============================================================================
// advanced_primitive_test_dump_32.h
// DEBUG PARAMETER DUMP for advanced_primitive_test
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef ADVANCED_PRIMITIVE_TEST_DUMP_32_H
#define ADVANCED_PRIMITIVE_TEST_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: advanced_primitive_test
 * Hash:   0xBF393EA6
 * Trees:  1
 * Records: 1
 * Strings: 20
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x16F84D20 "State machine test started "
 * [0x0001] (  1) hash=0xBE1A3917 "event_actions_fn[1]"
 * [0x0002] (  2) hash=0x470F9915 "if then branch  start"
 * [0x0003] (  3) hash=0xFF36094C "if then branch  end"
 * [0x0004] (  4) hash=0x298BC715 "if else branch start"
 * [0x0005] (  5) hash=0x12FF074C "if else branch end"
 * [0x0006] (  6) hash=0x748EB390 "event_actions_fn[1] terminated"
 * [0x0007] (  7) hash=0xBE20F4DC "event_actions_fn[2]"
 * [0x0008] (  8) hash=0x97AE2D3D "event_actions_fn[2] terminated"
 * [0x0009] (  9) hash=0x821E57D1 "event_actions_fn[3]"
 * [0x000A] ( 10) hash=0xCD84EEA6 "event_actions_fn[3] terminated"
 * [0x000B] ( 11) hash=0x8226A696 "event_actions_fn[4]"
 * [0x000C] ( 12) hash=0xC3158383 "event_actions_fn[4] terminated"
 * [0x000D] ( 13) hash=0xA5B2C752 "Matched EVENT_1 or EVENT_3"
 * [0x000E] ( 14) hash=0x3A3FE766 "Matched EVENT_2"
 * [0x000F] ( 15) hash=0x3C3FEA8C "Matched EVENT_4"
 * [0x0010] ( 16) hash=0x89FA9636 "State 0"
 * [0x0011] ( 17) hash=0x8AFA97C9 "State 1"
 * [0x0012] ( 18) hash=0x87FA9310 "State 2"
 * [0x0013] ( 19) hash=0x8300AF51 "State 2 terminated"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0001] ( 1) hash=0xCEBBEFA4 SE_LOG
 *   [0x0002] ( 2) hash=0x8BA62F1B DISPLAY_EVENT_INFO
 *   [0x0003] ( 3) hash=0xCF729BCE SE_QUEUE_EVENT
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0xF3EDFC75 SE_EVENT_DISPATCH
 *   [0x0002] ( 2) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0003] ( 3) hash=0x1E860193 SE_IF_THEN_ELSE
 *   [0x0004] ( 4) hash=0x8CD80263 SE_RETURN_PIPELINE_RESET
 *   [0x0005] ( 5) hash=0x4AC84487 SE_RETURN_PIPELINE_HALT
 *   [0x0006] ( 6) hash=0xCE0831A2 SE_COND
 *   [0x0007] ( 7) hash=0x5EEDA8E9 SE_STATE_MACHINE
 *   [0x0008] ( 8) hash=0x0C3460EB SE_TICK_DELAY
 *   [0x0009] ( 9) hash=0x0A24332A SE_FORK
 *   [0x000A] (10) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *
 * PRED FUNCTIONS (type=0x0A, with 0x40=p_call_composite):
 *   [0x0000] ( 0) hash=0x80659F81 SE_CHECK_EVENT
 *   [0x0001] ( 1) hash=0x0C125BC2 SE_TRUE
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: state_machine_blackboard (size=20, align=4, hash=0xC89D038C)
 *   [ 0] off=0x0000 size= 4 hash=0x783132F6 state
 *   [ 1] off=0x0004 size= 4 hash=0x0BFA174C event_data_1
 *   [ 2] off=0x0008 size= 4 hash=0x0EFA1C05 event_data_2
 *   [ 3] off=0x000C size= 4 hash=0x0DFA1A72 event_data_3
 *   [ 4] off=0x0010 size= 4 hash=0x08FA1293 event_data_4
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: dispatch_test
 *   hash=0xD00FA9D8 nodes=93 ptrs=3
 *   record=state_machine_blackboard (hash=0xC89D038C)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    348      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *    3    ONESHOT+SR[0x48]      2      0  idx_to_ptr=0
 *    4      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *    5      UINT[0x01]           -      -  0 (0x00000000)
 *    6    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *    7    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    8    ONESHOT   [0x08]      7      1  idx_to_ptr=0
 *    9      STR_IDX[0x0D]        0     27  "State machine test started "
 *   10    CLOSE[0x06]          0      -  (end SE_LOG)
 *   11    OPEN_CALL[0x07]    175      0  SE_EVENT_DISPATCH hash=0xF3EDFC75
 *   12    MAIN      [0x09]     11      1  idx_to_ptr=0
 *   13      INT[0x00]            -      -  1 (0x00000001)
 *   14      OPEN_CALL[0x07]     63      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   15      MAIN      [0x09]     14      2  idx_to_ptr=0
 *   16        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   17        ONESHOT   [0x08]     16      1  idx_to_ptr=0
 *   18          STR_IDX[0x0D]        1     19  "event_actions_fn[1]"
 *   19        CLOSE[0x06]          0      -  (end SE_LOG)
 *   20        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   21        ONESHOT   [0x08]     20      2  idx_to_ptr=0
 *   22        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   23        OPEN_CALL[0x07]     41      0  SE_IF_THEN_ELSE hash=0x1E860193
 *   24        MAIN      [0x09]     23      3  idx_to_ptr=0
 *   25          OPEN_CALL[0x07]      4      0  SE_CHECK_EVENT hash=0x80659F81
 *   26          PRED      [0x0A]     25      0  idx_to_ptr=0
 *   27            INT[0x00]            -      -  1 (0x00000001)
 *   28            INT[0x00]            -      -  3 (0x00000003)
 *   29          CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *   30          OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   31          MAIN      [0x09]     30      2  idx_to_ptr=0
 *   32            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   33            ONESHOT   [0x08]     32      1  idx_to_ptr=0
 *   34              STR_IDX[0x0D]        2     21  "if then branch  start"
 *   35            CLOSE[0x06]          0      -  (end SE_LOG)
 *   36            OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   37            ONESHOT   [0x08]     36      2  idx_to_ptr=0
 *   38            CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   39            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   40            ONESHOT   [0x08]     39      1  idx_to_ptr=0
 *   41              STR_IDX[0x0D]        3     19  "if then branch  end"
 *   42            CLOSE[0x06]          0      -  (end SE_LOG)
 *   43            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   44            MAIN      [0x09]     43      4  idx_to_ptr=0
 *   45            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   46          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   47          OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   48          MAIN      [0x09]     47      2  idx_to_ptr=0
 *   49            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   50            ONESHOT   [0x08]     49      1  idx_to_ptr=0
 *   51              STR_IDX[0x0D]        4     20  "if else branch start"
 *   52            CLOSE[0x06]          0      -  (end SE_LOG)
 *   53            OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   54            ONESHOT   [0x08]     53      2  idx_to_ptr=0
 *   55            CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   56            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   57            ONESHOT   [0x08]     56      1  idx_to_ptr=0
 *   58              STR_IDX[0x0D]        5     18  "if else branch end"
 *   59            CLOSE[0x06]          0      -  (end SE_LOG)
 *   60            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   61            MAIN      [0x09]     60      4  idx_to_ptr=0
 *   62            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   63          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   64        CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *   65        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   66        ONESHOT   [0x08]     65      0  idx_to_ptr=0
 *   67          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   68          UINT[0x01]           -      -  1 (0x00000001)
 *   69        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   70        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   71        ONESHOT   [0x08]     70      1  idx_to_ptr=0
 *   72          STR_IDX[0x0D]        6     30  "event_actions_fn[1] terminated"
 *   73        CLOSE[0x06]          0      -  (end SE_LOG)
 *   74        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   75        MAIN      [0x09]     74      4  idx_to_ptr=0
 *   76        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   77      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   78      INT[0x00]            -      -  3 (0x00000003)
 *   79      OPEN_CALL[0x07]     21      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   80      MAIN      [0x09]     79      2  idx_to_ptr=0
 *   81        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   82        ONESHOT   [0x08]     81      1  idx_to_ptr=0
 *   83          STR_IDX[0x0D]        7     19  "event_actions_fn[2]"
 *   84        CLOSE[0x06]          0      -  (end SE_LOG)
 *   85        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   86        ONESHOT   [0x08]     85      2  idx_to_ptr=0
 *   87        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   88        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   89        ONESHOT   [0x08]     88      0  idx_to_ptr=0
 *   90          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   91          UINT[0x01]           -      -  2 (0x00000002)
 *   92        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   93        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   94        ONESHOT   [0x08]     93      1  idx_to_ptr=0
 *   95          STR_IDX[0x0D]        8     30  "event_actions_fn[2] terminated"
 *   96        CLOSE[0x06]          0      -  (end SE_LOG)
 *   97        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   98        MAIN      [0x09]     97      4  idx_to_ptr=0
 *   99        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  100      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  101      INT[0x00]            -      -  2 (0x00000002)
 *  102      OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  103      MAIN      [0x09]    102      2  idx_to_ptr=0
 *  104        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  105        ONESHOT   [0x08]    104      1  idx_to_ptr=0
 *  106          STR_IDX[0x0D]        9     19  "event_actions_fn[3]"
 *  107        CLOSE[0x06]          0      -  (end SE_LOG)
 *  108        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  109        ONESHOT   [0x08]    108      2  idx_to_ptr=0
 *  110        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  111        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  112        ONESHOT   [0x08]    111      1  idx_to_ptr=0
 *  113          STR_IDX[0x0D]       10     30  "event_actions_fn[3] terminated"
 *  114        CLOSE[0x06]          0      -  (end SE_LOG)
 *  115        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  116        MAIN      [0x09]    115      4  idx_to_ptr=0
 *  117        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  118      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  119      INT[0x00]            -      -  4 (0x00000004)
 *  120      OPEN_CALL[0x07]     58      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  121      MAIN      [0x09]    120      2  idx_to_ptr=0
 *  122        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  123        ONESHOT   [0x08]    122      1  idx_to_ptr=0
 *  124          STR_IDX[0x0D]       11     19  "event_actions_fn[4]"
 *  125        CLOSE[0x06]          0      -  (end SE_LOG)
 *  126        OPEN_CALL[0x07]     41      0  SE_IF_THEN_ELSE hash=0x1E860193
 *  127        MAIN      [0x09]    126      3  idx_to_ptr=0
 *  128          OPEN_CALL[0x07]      4      0  SE_CHECK_EVENT hash=0x80659F81
 *  129          PRED      [0x0A]    128      0  idx_to_ptr=0
 *  130            INT[0x00]            -      -  1 (0x00000001)
 *  131            INT[0x00]            -      -  3 (0x00000003)
 *  132          CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *  133          OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  134          MAIN      [0x09]    133      2  idx_to_ptr=0
 *  135            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  136            ONESHOT   [0x08]    135      1  idx_to_ptr=0
 *  137              STR_IDX[0x0D]        2     21  "if then branch  start"
 *  138            CLOSE[0x06]          0      -  (end SE_LOG)
 *  139            OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  140            ONESHOT   [0x08]    139      2  idx_to_ptr=0
 *  141            CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  142            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  143            ONESHOT   [0x08]    142      1  idx_to_ptr=0
 *  144              STR_IDX[0x0D]        3     19  "if then branch  end"
 *  145            CLOSE[0x06]          0      -  (end SE_LOG)
 *  146            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  147            MAIN      [0x09]    146      4  idx_to_ptr=0
 *  148            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  149          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  150          OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  151          MAIN      [0x09]    150      2  idx_to_ptr=0
 *  152            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  153            ONESHOT   [0x08]    152      1  idx_to_ptr=0
 *  154              STR_IDX[0x0D]        4     20  "if else branch start"
 *  155            CLOSE[0x06]          0      -  (end SE_LOG)
 *  156            OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  157            ONESHOT   [0x08]    156      2  idx_to_ptr=0
 *  158            CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  159            OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  160            ONESHOT   [0x08]    159      1  idx_to_ptr=0
 *  161              STR_IDX[0x0D]        5     18  "if else branch end"
 *  162            CLOSE[0x06]          0      -  (end SE_LOG)
 *  163            OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  164            MAIN      [0x09]    163      4  idx_to_ptr=0
 *  165            CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  166          CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  167        CLOSE[0x06]          0      -  (end SE_IF_THEN_ELSE)
 *  168        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  169        ONESHOT   [0x08]    168      2  idx_to_ptr=0
 *  170        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  171        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  172        ONESHOT   [0x08]    171      1  idx_to_ptr=0
 *  173          STR_IDX[0x0D]       12     30  "event_actions_fn[4] terminated"
 *  174        CLOSE[0x06]          0      -  (end SE_LOG)
 *  175        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  176        MAIN      [0x09]    175      4  idx_to_ptr=0
 *  177        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  178      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  179      INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *  180      OPEN_CALL[0x07]      5      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  181      MAIN      [0x09]    180      2  idx_to_ptr=0
 *  182        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_HALT hash=0x4AC84487
 *  183        MAIN      [0x09]    182      5  idx_to_ptr=0
 *  184        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_HALT)
 *  185      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  186    CLOSE[0x06]          0      -  (end SE_EVENT_DISPATCH)
 *  187    OPEN_CALL[0x07]     63      0  SE_COND hash=0xCE0831A2
 *  188    MAIN      [0x09]    187      6  idx_to_ptr=0
 *  189      OPEN_CALL[0x07]      4      0  SE_CHECK_EVENT hash=0x80659F81
 *  190      PRED      [0x0A]    189      0  idx_to_ptr=0
 *  191        INT[0x00]            -      -  1 (0x00000001)
 *  192        INT[0x00]            -      -  3 (0x00000003)
 *  193      CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *  194      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  195      MAIN      [0x09]    194      2  idx_to_ptr=0
 *  196        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  197        ONESHOT   [0x08]    196      1  idx_to_ptr=0
 *  198          STR_IDX[0x0D]       13     26  "Matched EVENT_1 or EVENT_3"
 *  199        CLOSE[0x06]          0      -  (end SE_LOG)
 *  200        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  201        ONESHOT   [0x08]    200      2  idx_to_ptr=0
 *  202        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  203        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  204        MAIN      [0x09]    203      4  idx_to_ptr=0
 *  205        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  206      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  207      OPEN_CALL[0x07]      3      0  SE_CHECK_EVENT hash=0x80659F81
 *  208      PRED      [0x0A]    207      0  idx_to_ptr=0
 *  209        INT[0x00]            -      -  2 (0x00000002)
 *  210      CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *  211      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  212      MAIN      [0x09]    211      2  idx_to_ptr=0
 *  213        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  214        ONESHOT   [0x08]    213      1  idx_to_ptr=0
 *  215          STR_IDX[0x0D]       14     15  "Matched EVENT_2"
 *  216        CLOSE[0x06]          0      -  (end SE_LOG)
 *  217        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  218        ONESHOT   [0x08]    217      2  idx_to_ptr=0
 *  219        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  220        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  221        MAIN      [0x09]    220      4  idx_to_ptr=0
 *  222        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  223      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  224      OPEN_CALL[0x07]      3      0  SE_CHECK_EVENT hash=0x80659F81
 *  225      PRED      [0x0A]    224      0  idx_to_ptr=0
 *  226        INT[0x00]            -      -  4 (0x00000004)
 *  227      CLOSE[0x06]          0      -  (end SE_CHECK_EVENT)
 *  228      OPEN_CALL[0x07]     12      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  229      MAIN      [0x09]    228      2  idx_to_ptr=0
 *  230        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  231        ONESHOT   [0x08]    230      1  idx_to_ptr=0
 *  232          STR_IDX[0x0D]       15     15  "Matched EVENT_4"
 *  233        CLOSE[0x06]          0      -  (end SE_LOG)
 *  234        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *  235        ONESHOT   [0x08]    234      2  idx_to_ptr=0
 *  236        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *  237        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  238        MAIN      [0x09]    237      4  idx_to_ptr=0
 *  239        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  240      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  241      OPEN_CALL[0x07]      2      0  SE_TRUE hash=0x0C125BC2
 *  242      PRED      [0x0A]    241      1  idx_to_ptr=0
 *  243      CLOSE[0x06]          0      -  (end SE_TRUE)
 *  244      OPEN_CALL[0x07]      5      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  245      MAIN      [0x09]    244      2  idx_to_ptr=0
 *  246        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  247        MAIN      [0x09]    246      4  idx_to_ptr=0
 *  248        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  249      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  250    CLOSE[0x06]          0      -  (end SE_COND)
 *  251    OPEN_CALL[0x07]     96      0  SE_STATE_MACHINE hash=0x5EEDA8E9
 *  252    MAIN      [0x09]    251      7  idx_to_ptr=0
 *  253      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *  254      INT[0x00]            -      -  0 (0x00000000)
 *  255      OPEN_CALL[0x07]     35      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  256      MAIN      [0x09]    255      2  idx_to_ptr=0
 *  257        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  258        ONESHOT   [0x08]    257      1  idx_to_ptr=0
 *  259          STR_IDX[0x0D]       16      7  "State 0"
 *  260        CLOSE[0x06]          0      -  (end SE_LOG)
 *  261        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  262        MAIN+PTR  [0x89]    261      8  idx_to_ptr=0
 *  263          INT[0x00]            -      -  20 (0x00000014)
 *  264        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  265        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  266        ONESHOT   [0x08]    265      0  idx_to_ptr=0
 *  267          FIELD[0x0B]          4      4  event_data_1 (off=0x0004, hash=0x0BFA174C)
 *  268          FLOAT[0x02]          -      -  1.1
 *  269        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  270        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  271        ONESHOT   [0x08]    270      0  idx_to_ptr=0
 *  272          FIELD[0x0B]          8      4  event_data_2 (off=0x0008, hash=0x0EFA1C05)
 *  273          FLOAT[0x02]          -      -  2.2
 *  274        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  275        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  276        ONESHOT   [0x08]    275      3  idx_to_ptr=0
 *  277          UINT[0x01]           -      -  1 (0x00000001)
 *  278          UINT[0x01]           -      -  1 (0x00000001)
 *  279          FIELD[0x0B]          4      4  event_data_1 (off=0x0004, hash=0x0BFA174C)
 *  280        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  281        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  282        ONESHOT   [0x08]    281      3  idx_to_ptr=0
 *  283          UINT[0x01]           -      -  1 (0x00000001)
 *  284          UINT[0x01]           -      -  2 (0x00000002)
 *  285          FIELD[0x0B]          8      4  event_data_2 (off=0x0008, hash=0x0EFA1C05)
 *  286        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  287        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  288        MAIN      [0x09]    287      4  idx_to_ptr=0
 *  289        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  290      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  291      INT[0x00]            -      -  1 (0x00000001)
 *  292      OPEN_CALL[0x07]     35      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  293      MAIN      [0x09]    292      2  idx_to_ptr=0
 *  294        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  295        ONESHOT   [0x08]    294      1  idx_to_ptr=0
 *  296          STR_IDX[0x0D]       17      7  "State 1"
 *  297        CLOSE[0x06]          0      -  (end SE_LOG)
 *  298        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  299        MAIN+PTR  [0x89]    298      8  idx_to_ptr=1
 *  300          INT[0x00]            -      -  20 (0x00000014)
 *  301        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  302        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  303        ONESHOT   [0x08]    302      0  idx_to_ptr=0
 *  304          FIELD[0x0B]         12      4  event_data_3 (off=0x000C, hash=0x0DFA1A72)
 *  305          FLOAT[0x02]          -      -  3.3
 *  306        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  307        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  308        ONESHOT   [0x08]    307      0  idx_to_ptr=0
 *  309          FIELD[0x0B]         16      4  event_data_4 (off=0x0010, hash=0x08FA1293)
 *  310          FLOAT[0x02]          -      -  4.4
 *  311        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  312        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  313        ONESHOT   [0x08]    312      3  idx_to_ptr=0
 *  314          UINT[0x01]           -      -  1 (0x00000001)
 *  315          UINT[0x01]           -      -  3 (0x00000003)
 *  316          FIELD[0x0B]         12      4  event_data_3 (off=0x000C, hash=0x0DFA1A72)
 *  317        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  318        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  319        ONESHOT   [0x08]    318      3  idx_to_ptr=0
 *  320          UINT[0x01]           -      -  1 (0x00000001)
 *  321          UINT[0x01]           -      -  4 (0x00000004)
 *  322          FIELD[0x0B]         16      4  event_data_4 (off=0x0010, hash=0x08FA1293)
 *  323        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  324        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  325        MAIN      [0x09]    324      4  idx_to_ptr=0
 *  326        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  327      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  328      INT[0x00]            -      -  2 (0x00000002)
 *  329      OPEN_CALL[0x07]     17      0  SE_FORK hash=0x0A24332A
 *  330      MAIN      [0x09]    329      9  idx_to_ptr=0
 *  331        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  332        ONESHOT   [0x08]    331      1  idx_to_ptr=0
 *  333          STR_IDX[0x0D]       18      7  "State 2"
 *  334        CLOSE[0x06]          0      -  (end SE_LOG)
 *  335        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  336        MAIN+PTR  [0x89]    335      8  idx_to_ptr=2
 *  337          INT[0x00]            -      -  20 (0x00000014)
 *  338        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  339        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  340        ONESHOT   [0x08]    339      1  idx_to_ptr=0
 *  341          STR_IDX[0x0D]       19     18  "State 2 terminated"
 *  342        CLOSE[0x06]          0      -  (end SE_LOG)
 *  343        OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  344        MAIN      [0x09]    343     10  idx_to_ptr=0
 *  345        CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  346      CLOSE[0x06]          0      -  (end SE_FORK)
 *  347    CLOSE[0x06]          0      -  (end SE_STATE_MACHINE)
 *  348  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 349
 */

#endif // ADVANCED_PRIMITIVE_TEST_DUMP_32_H
