// ============================================================================
// black_board_user_registration.c
// User function registration for black_board
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "black_board.h"
#include "black_board_user_functions.h"
#include "s_engine_module.h"

// Oneshot function entries
static s_expr_fn_entry_t black_board_oneshot_entries[] = {
    { 0xCDD8F540, (void*)bb_write_verify_int32 },
    { 0x4B00A0D5, (void*)bb_write_verify_uint32 },
    { 0x2D63582E, (void*)bb_write_verify_float },
    { 0x61D18F77, (void*)bb_write_verify_int64 },
    { 0x46F3CE96, (void*)bb_write_verify_uint64 },
    { 0x9616C541, (void*)bb_write_verify_double },
    { 0xAC39405C, (void*)slot_write_verify_int32 },
    { 0xC472CE81, (void*)slot_write_verify_uint32 },
    { 0xE03CFADA, (void*)slot_write_verify_float },
    { 0x28453C83, (void*)slot_write_verify_int64 },
    { 0x387A40E2, (void*)slot_write_verify_uint64 },
    { 0xC62CCE4D, (void*)slot_write_verify_double },
    { 0x3CB5CD89, (void*)slot_write_verify_string },
    { 0xA5F6575B, (void*)slot_write_verify_int32_element },
    { 0xA292F461, (void*)slot_write_verify_float32_array },
    { 0xBAE5CE26, (void*)slot_verify_float },
};

static const s_expr_fn_table_t black_board_oneshot_table = {
    .entries = black_board_oneshot_entries,
    .count = 16
};

// Table accessors
const s_expr_fn_table_t* black_board_get_oneshot_table(void) {
    return &black_board_oneshot_table;
}

const s_expr_fn_table_t* black_board_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* black_board_get_pred_table(void) {
    return NULL;
}

// Register all user functions with module
void black_board_register_all(s_expr_module_t* module) {
    s_expr_module_register_oneshot(module, &black_board_oneshot_table);
}
