// ============================================================================
// black_board_records.h
// Generated record structures for black_board
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef BLACK_BOARD_RECORDS_H
#define BLACK_BOARD_RECORDS_H

#include <stdint.h>
#include <stdbool.h>

// Forward declarations
typedef struct ScalarDemo_s ScalarDemo_t;
typedef struct ArrayDemo_s ArrayDemo_t;
typedef struct Vector3_s Vector3_t;
typedef struct Transform_s Transform_t;
typedef struct LinkedNode_s LinkedNode_t;

// Record: ScalarDemo (size=40, align=8)
struct ScalarDemo_s {
    int32_t counter;  // offset=0, size=4
    uint32_t flags;  // offset=4, size=4
    float temperature;  // offset=8, size=4
    int64_t timestamp;  // offset=16, size=8
    uint64_t checksum;  // offset=24, size=8
    double precise_value;  // offset=32, size=8
};

// Array length constants for ArrayDemo
#define ARRAYDEMO_NAME_LEN 32
#define ARRAYDEMO_SHORT_TAG_LEN 4
#define ARRAYDEMO_INT_VALUES_LEN 4
#define ARRAYDEMO_FLOAT_VALUES_LEN 4

// Record: ArrayDemo (size=68, align=4)
struct ArrayDemo_s {
    char name[ARRAYDEMO_NAME_LEN];  // offset=0, size=32 (char array)
    char short_tag[ARRAYDEMO_SHORT_TAG_LEN];  // offset=32, size=4 (char array)
    int32_t int_values[ARRAYDEMO_INT_VALUES_LEN];  // offset=36, size=16 (int32 array)
    float float_values[ARRAYDEMO_FLOAT_VALUES_LEN];  // offset=52, size=16 (float32 array)
};

// Record: Vector3 (size=12, align=4)
struct Vector3_s {
    float x;  // offset=0, size=4
    float y;  // offset=4, size=4
    float z;  // offset=8, size=4
};

// Record: Transform (size=28, align=4)
struct Transform_s {
    Vector3_t position;  // offset=0, size=12
    Vector3_t rotation;  // offset=12, size=12
    float scale;  // offset=24, size=4
};

// Record: LinkedNode (size=24, align=8)
struct LinkedNode_s {
    int32_t value;  // offset=0, size=4
    uint32_t pad;  // offset=4, size=4
    uint64_t next;  // offset=8, size=8 (ptr64)
    uint64_t data;  // offset=16, size=8 (ptr64)
};

#endif // BLACK_BOARD_RECORDS_H
