// ============================================================================
// black_board_module_rom.c
// Generated S-expression module for black_board (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "black_board_records.h"
#include "black_board.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern void bb_write_verify_int32(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void bb_write_verify_uint32(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void bb_write_verify_float(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void bb_write_verify_int64(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void bb_write_verify_uint64(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void bb_write_verify_double(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_int32(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_uint32(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_float(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_int64(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_uint64(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_double(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_string(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_int32_element(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_write_verify_float32_array(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);
extern void slot_verify_float(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

static const s_expr_field_desc_t black_board_ScalarDemo_fields[] = {
    { .name_hash = 0x9CACDE23U, .offset = 0, .size = 4 },
    { .name_hash = 0x9C677A2CU, .offset = 4, .size = 4 },
    { .name_hash = 0xE9F2A935U, .offset = 8, .size = 4 },
    { .name_hash = 0xB283D523U, .offset = 16, .size = 8 },
    { .name_hash = 0x6015CB92U, .offset = 24, .size = 8 },
    { .name_hash = 0x38EE5A4CU, .offset = 32, .size = 8 }
};

static const s_expr_field_desc_t black_board_ArrayDemo_fields[] = {
    { .name_hash = 0x8D39BDE6U, .offset = 0, .size = 32 },
    { .name_hash = 0x255CDD9EU, .offset = 32, .size = 4 },
    { .name_hash = 0xEA35C039U, .offset = 36, .size = 16 },
    { .name_hash = 0xF3AA6974U, .offset = 52, .size = 16 }
};

static const s_expr_field_desc_t black_board_Vector3_fields[] = {
    { .name_hash = 0xFD0C5087U, .offset = 0, .size = 4 },
    { .name_hash = 0xFC0C4EF4U, .offset = 4, .size = 4 },
    { .name_hash = 0xFF0C53ADU, .offset = 8, .size = 4 }
};

static const s_expr_field_desc_t black_board_Transform_fields[] = {
    { .name_hash = 0x934F4E0AU, .offset = 0, .size = 12 },
    { .name_hash = 0x21AC415FU, .offset = 12, .size = 12 },
    { .name_hash = 0x82971C71U, .offset = 24, .size = 4 }
};

static const s_expr_field_desc_t black_board_LinkedNode_fields[] = {
    { .name_hash = 0x425ED3CAU, .offset = 0, .size = 4 },
    { .name_hash = 0x5955FEAAU, .offset = 4, .size = 4 },
    { .name_hash = 0x5CB68DE8U, .offset = 8, .size = 8 },
    { .name_hash = 0xD872E2A5U, .offset = 16, .size = 8 }
};

static const s_expr_record_desc_t black_board_records[] = {
    { .name_hash = 0xEE7D8F2EU, .total_size = 40, .field_count = 6, .fields = black_board_ScalarDemo_fields },
    { .name_hash = 0xB7FC2169U, .total_size = 68, .field_count = 4, .fields = black_board_ArrayDemo_fields },
    { .name_hash = 0x840071C3U, .total_size = 12, .field_count = 3, .fields = black_board_Vector3_fields },
    { .name_hash = 0xAD82ABBBU, .total_size = 28, .field_count = 3, .fields = black_board_Transform_fields },
    { .name_hash = 0xA3AC758CU, .total_size = 24, .field_count = 4, .fields = black_board_LinkedNode_fields }
};

// Tree: demo_blackboard_access (params=33, nodes=7)
static const s_expr_param_t black_board_demo_blackboard_access_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 100 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 100 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 1 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0xDEADBEEFU },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0xDEADBEEFU },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 11 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 2 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 98.6f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 98.6f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1912276171 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1912276171 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 20 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 21 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x0U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 25 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 26 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 5 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.71828183f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.71828183f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 }
};

// Tree: demo_slot_access (params=39, nodes=7)
static const s_expr_param_t black_board_demo_slot_access_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 38, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 6 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 42 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 42 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 6 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 7 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 7 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0xCAFEBABEU },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0xCAFEBABEU },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 13 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 72.5f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 72.5f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 9 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 16, .field_size = 8 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1286608618 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1286608618 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 25 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 10 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 24, .field_size = 8 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x0U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0x0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 30 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 31 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 11 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 32, .field_size = 8 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.41421356f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.41421356f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 36 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 38, .parent_offset = 0 }
};

// Tree: demo_array_access (params=55, nodes=8)
static const s_expr_param_t black_board_demo_array_access_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 54, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 12 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 32 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 13 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 13 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 6 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 7 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 12 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 32, .field_size = 4 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 3 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 13 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 13 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 36, .field_size = 16 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 100 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 100 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 19 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 20 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 13 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 36, .field_size = 16 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 200 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 200 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 26 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 27 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 13 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 36, .field_size = 16 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 300 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 300 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 33 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 34 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 13 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 36, .field_size = 16 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 400 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 400 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 6, .parent_offset = 40 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 11, .parent_offset = 41 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 14 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 52, .field_size = 16 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.1f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.2f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 3.3f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 4.4f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.1f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.2f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 3.3f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 4.4f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 11, .parent_offset = 52 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 54, .parent_offset = 0 }
};

// Tree: demo_nested_access (params=33, nodes=6)
static const s_expr_param_t black_board_demo_nested_access_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 10.0f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 10.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 6 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 7 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 20.0f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 20.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 13 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 30.0f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 30.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 12, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 45.0f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 45.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 25 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 24, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.5f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.5f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 32, .parent_offset = 0 }
};

// Tree: demo_constants (params=29, nodes=6)
static const s_expr_param_t black_board_demo_constants_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 28, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 15 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 0.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 15 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 10 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 11 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 15 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 0.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 15 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 16 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 8 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 5.0f },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 5.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 21 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 22 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 15 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.0f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 26 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 28, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t black_board_trees[] = {
    {
        .name_hash = 0xF584F515U,
        .record_hash = 0xEE7D8F2EU,
        .params = black_board_demo_blackboard_access_params,
        .param_count = 33,
        .func_node_count = 7,
        .pointer_count = 0,
        .defaults_index = 2,
    },
    {
        .name_hash = 0x2435F6EAU,
        .record_hash = 0xEE7D8F2EU,
        .params = black_board_demo_slot_access_params,
        .param_count = 39,
        .func_node_count = 7,
        .pointer_count = 0,
        .defaults_index = 2,
    },
    {
        .name_hash = 0x6BB11173U,
        .record_hash = 0xB7FC2169U,
        .params = black_board_demo_array_access_params,
        .param_count = 55,
        .func_node_count = 8,
        .pointer_count = 0,
        .defaults_index = 65535,
    },
    {
        .name_hash = 0x68FA6C13U,
        .record_hash = 0xAD82ABBBU,
        .params = black_board_demo_nested_access_params,
        .param_count = 33,
        .func_node_count = 6,
        .pointer_count = 0,
        .defaults_index = 1,
    },
    {
        .name_hash = 0x459ACD44U,
        .record_hash = 0x840071C3U,
        .params = black_board_demo_constants_params,
        .param_count = 29,
        .func_node_count = 6,
        .pointer_count = 0,
        .defaults_index = 0,
    }
};

static const s_expr_oneshot_fn_t black_board_oneshot_fns[] = {
    bb_write_verify_int32,  // 0: bb_write_verify_int32
    bb_write_verify_uint32,  // 1: bb_write_verify_uint32
    bb_write_verify_float,  // 2: bb_write_verify_float
    bb_write_verify_int64,  // 3: bb_write_verify_int64
    bb_write_verify_uint64,  // 4: bb_write_verify_uint64
    bb_write_verify_double,  // 5: bb_write_verify_double
    slot_write_verify_int32,  // 6: slot_write_verify_int32
    slot_write_verify_uint32,  // 7: slot_write_verify_uint32
    slot_write_verify_float,  // 8: slot_write_verify_float
    slot_write_verify_int64,  // 9: slot_write_verify_int64
    slot_write_verify_uint64,  // 10: slot_write_verify_uint64
    slot_write_verify_double,  // 11: slot_write_verify_double
    slot_write_verify_string,  // 12: slot_write_verify_string
    slot_write_verify_int32_element,  // 13: slot_write_verify_int32_element
    slot_write_verify_float32_array,  // 14: slot_write_verify_float32_array
    slot_verify_float  // 15: slot_verify_float
};

static const s_expr_main_fn_t black_board_main_fns[] = {
    se_sequence  // 0: SE_SEQUENCE
};

static const s_expr_pred_fn_t black_board_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t black_board_module_rom = {
    .name_hash = 0xCDCE8FEFU,
    .is_64bit = false,
    .trees = black_board_trees,
    .tree_count = 5,
    .records = black_board_records,
    .record_count = 5,
    .string_table = black_board_strings,
    .string_count = 2,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = black_board_oneshot_fns,
    .oneshot_count = 16,
    .main_fns = black_board_main_fns,
    .main_count = 1,
    .pred_fns = black_board_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 8,
    .max_pointer_count = 0,
    .max_param_count = 55,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

