// ============================================================================
// dispatch_test_user_registration.c
// User function registration for dispatch_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// NOTE: Builtin functions (SE_*) are registered via s_engine_register_builtins()
// ============================================================================

#include "dispatch_test.h"
#include "dispatch_test_user_functions.h"
#include "s_engine_module.h"

// Oneshot function entries
static s_expr_fn_entry_t dispatch_test_oneshot_entries[] = {
    { 0x8BA62F1B, (void*)display_event_info },
};

static const s_expr_fn_table_t dispatch_test_oneshot_table = {
    .entries = dispatch_test_oneshot_entries,
    .count = 1
};

// Table accessors
const s_expr_fn_table_t* dispatch_test_get_oneshot_table(void) {
    return &dispatch_test_oneshot_table;
}

const s_expr_fn_table_t* dispatch_test_get_main_table(void) {
    return NULL;
}

const s_expr_fn_table_t* dispatch_test_get_pred_table(void) {
    return NULL;
}

// Register all user functions with module
void dispatch_test_register_all(s_expr_module_t* module) {
    s_expr_module_register_oneshot(module, &dispatch_test_oneshot_table);
}
