// ============================================================================
// dispatch_test_module_rom.c
// Generated S-expression module for dispatch_test (M-port: const ROM tables)
// DO NOT EDIT - Generated by s_expr_dsl v5.3 C-emit
// ============================================================================

#include "s_engine_types.h"
#include "s_engine_module.h"
#include "s_engine_eval.h"
#include "s_engine_node.h"
#include "s_engine_exception.h"
#include "s_engine_event_queue.h"
#include "s_engine_stack.h"
#include "se_dict_string.h"
#include "se_dict_hash.h"
#include "s_engine_builtins_shared_helpers.h"
#include "s_engine_builtins_pred.h"
#include "s_engine_builtins_delays.h"
#include "s_engine_builtins_flow_control.h"
#include "s_engine_builtins_dispatch.h"
#include "s_engine_builtins_verify.h"
#include "s_engine_builtins_oneshot.h"
#include "s_engine_builtins_return_codes.h"
#include "s_engine_builtins_quads.h"
#include "s_engine_builtins_dict.h"
#include "s_engine_builtins_stack.h"
#include "s_engine_builtins_spawn.h"
#include "s_engine_rom.h"  // s_engine_rom_t (M-port)
#include "dispatch_test_records.h"
#include "dispatch_test.h"

// Forward declarations for USER functions only.
// Builtins are visible via the builtins_*.h includes above (static defs).
// Linker resolves user fns or errors at link time.
extern void display_event_info(s_expr_tree_instance_t*, const s_expr_param_t*, uint16_t, s_expr_event_type_t, uint16_t, void*);

static const s_expr_field_desc_t dispatch_test_state_machine_blackboard_fields[] = {
    { .name_hash = 0x783132F6U, .offset = 0, .size = 4 },
    { .name_hash = 0x0BFA174CU, .offset = 4, .size = 4 },
    { .name_hash = 0x0EFA1C05U, .offset = 8, .size = 4 },
    { .name_hash = 0x0DFA1A72U, .offset = 12, .size = 4 },
    { .name_hash = 0x08FA1293U, .offset = 16, .size = 4 }
};

static const s_expr_record_desc_t dispatch_test_records[] = {
    { .name_hash = 0xC89D038CU, .total_size = 20, .field_count = 5, .fields = dispatch_test_state_machine_blackboard_fields }
};

// Tree: dispatch_test (params=262, nodes=66)
static const s_expr_param_t dispatch_test_dispatch_test_params[] = {
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 261, .parent_offset = 0 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 1 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 0U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 5 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 0, .str_len = 27 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 91, .parent_offset = 10 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 1 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 21, .parent_offset = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 4, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 1, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 13 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 2, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 16 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 17 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 9, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 21, .parent_offset = 23 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 3 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 21, .parent_offset = 25 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 10, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 11, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 3, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 12, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 2U },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 13 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 4, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 16 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 17 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 15, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 21, .parent_offset = 46 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 16, .parent_offset = 48 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 16, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 5, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 18, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 6, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 20, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 14 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 16, .parent_offset = 64 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 16, .parent_offset = 66 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 21, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 22, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 7, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 5 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 23, .func_index = 2 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 7 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 24, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 8, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 11 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 25, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 14 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 16, .parent_offset = 82 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 84 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 26, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 1 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 27, .func_index = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 89 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 91, .parent_offset = 101 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 60, .parent_offset = 102 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 28, .func_index = 5 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 3 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 29, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 30, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 9, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 31, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 32, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 10, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 33, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 20 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 22 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 34, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 35, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 11, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 1, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 36, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 37, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 12, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 38, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 39 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = -1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 41 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 39, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 40, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 13, .str_len = 19 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 2, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 2, .node_index = 41, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 5 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 42, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 14, .str_len = 30 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 43, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 58 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 60, .parent_offset = 162 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 96, .parent_offset = 163 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 44, .func_index = 7 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 0, .field_size = 4 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 0 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 35, .parent_offset = 3 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 45, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 46, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 15, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 3, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 3, .node_index = 47, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 20 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 48, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 1.1f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 13 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 49, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 2.2f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 50, .func_index = 3 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 4, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 25 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 51, .func_index = 3 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 2U },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 8, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 30 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 31 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 52, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 33 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 35, .parent_offset = 38 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 1 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 35, .parent_offset = 40 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 53, .func_index = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 54, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 16, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 4, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 4, .node_index = 55, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 20 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 56, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 12, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 3.3f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 13 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 14 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 57, .func_index = 0 },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 16, .field_size = 4 },
    { .type = 0x02, .index_to_pointer = 0, .float_val = 4.4f },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 4, .parent_offset = 18 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 19 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 58, .func_index = 3 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 3U },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 12, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 24 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 25 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 59, .func_index = 3 },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 1U },
    { .type = 0x01, .index_to_pointer = 0, .uint_val = 4U },
    { .type = 0x0B, .index_to_pointer = 0, .field_offset = 16, .field_size = 4 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 5, .parent_offset = 30 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 31 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 60, .func_index = 3 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 33 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 35, .parent_offset = 75 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 2 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 77 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 61, .func_index = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 1 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 62, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 17, .str_len = 7 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 4 },
    { .type = 0x07, .index_to_pointer = 5, .brace_idx = 3, .parent_offset = 5 },
    { .type = 0x89, .index_to_pointer = 5, .node_index = 63, .func_index = 6 },
    { .type = 0x00, .index_to_pointer = 0, .int_val = 20 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 8 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 9 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 64, .func_index = 1 },
    { .type = 0x0D, .index_to_pointer = 0, .str_index = 18, .str_len = 18 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 3, .parent_offset = 12 },
    { .type = 0x07, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 65, .func_index = 9 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 2, .parent_offset = 15 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 17, .parent_offset = 94 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 96, .parent_offset = 259 },
    { .type = 0x06, .index_to_pointer = 0, .brace_idx = 261, .parent_offset = 0 }
};

// Tree definitions
static const s_expr_tree_def_t dispatch_test_trees[] = {
    {
        .name_hash = 0xD00FA9D8U,
        .record_hash = 0xC89D038CU,
        .params = dispatch_test_dispatch_test_params,
        .param_count = 262,
        .func_node_count = 66,
        .pointer_count = 6,
        .defaults_index = 65535,
    }
};

static const s_expr_oneshot_fn_t dispatch_test_oneshot_fns[] = {
    se_set_field,  // 0: SE_SET_FIELD
    se_log,  // 1: SE_LOG
    display_event_info,  // 2: DISPLAY_EVENT_INFO
    se_queue_event  // 3: SE_QUEUE_EVENT
};

static const s_expr_main_fn_t dispatch_test_main_fns[] = {
    se_function_interface,  // 0: SE_FUNCTION_INTERFACE
    se_event_dispatch,  // 1: SE_EVENT_DISPATCH
    se_chain_flow,  // 2: SE_CHAIN_FLOW
    se_return_pipeline_reset,  // 3: SE_RETURN_PIPELINE_RESET
    se_return_pipeline_halt,  // 4: SE_RETURN_PIPELINE_HALT
    se_field_dispatch,  // 5: SE_FIELD_DISPATCH
    se_tick_delay,  // 6: SE_TICK_DELAY
    se_state_machine,  // 7: SE_STATE_MACHINE
    se_fork,  // 8: SE_FORK
    se_return_terminate  // 9: SE_RETURN_TERMINATE
};

static const s_expr_pred_fn_t dispatch_test_pred_fns[1] = { NULL };

// Top-level ROM handle (M-port)
const s_engine_rom_t dispatch_test_module_rom = {
    .name_hash = 0xD00FA9D8U,
    .is_64bit = false,
    .trees = dispatch_test_trees,
    .tree_count = 1,
    .records = dispatch_test_records,
    .record_count = 1,
    .string_table = dispatch_test_strings,
    .string_count = 19,
    .constants = NULL,
    .const_count = 0,
    .oneshot_fns = dispatch_test_oneshot_fns,
    .oneshot_count = 4,
    .main_fns = dispatch_test_main_fns,
    .main_count = 10,
    .pred_fns = dispatch_test_pred_fns,
    .pred_count = 0,
    .max_func_node_count = 66,
    .max_pointer_count = 6,
    .max_param_count = 262,
    .bump_buffer_size = 0,  // TODO: DSL-computed when bump allocator lands
};

