// ============================================================================
// dispatch_test_debug.h
// Debug hash reference for dispatch_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef DISPATCH_TEST_DEBUG_H
#define DISPATCH_TEST_DEBUG_H

// Oneshot functions
#define H_FFF84A15 0xFFF84A15  // SE_SET_FIELD
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_8BA62F1B 0x8BA62F1B  // DISPLAY_EVENT_INFO
#define H_CF729BCE 0xCF729BCE  // SE_QUEUE_EVENT

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_F3EDFC75 0xF3EDFC75  // SE_EVENT_DISPATCH
#define H_FFC1FAA4 0xFFC1FAA4  // SE_CHAIN_FLOW
#define H_8CD80263 0x8CD80263  // SE_RETURN_PIPELINE_RESET
#define H_4AC84487 0x4AC84487  // SE_RETURN_PIPELINE_HALT
#define H_A1C11B35 0xA1C11B35  // SE_FIELD_DISPATCH
#define H_0C3460EB 0x0C3460EB  // SE_TICK_DELAY
#define H_5EEDA8E9 0x5EEDA8E9  // SE_STATE_MACHINE
#define H_0A24332A 0x0A24332A  // SE_FORK
#define H_DFE64C74 0xDFE64C74  // SE_RETURN_TERMINATE

#endif // DISPATCH_TEST_DEBUG_H
