// ============================================================================
// dispatch_test_dump_32.h
// DEBUG PARAMETER DUMP for dispatch_test
// Mode: 32-bit
// Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef DISPATCH_TEST_DUMP_32_H
#define DISPATCH_TEST_DUMP_32_H

/*
 * PARAMETER TYPE CODES:
 *   0x00 INT          0x01 UINT         0x02 FLOAT        0x03 STR_HASH
 *   0x04 SLOT         0x05 OPEN         0x06 CLOSE        0x07 OPEN_CALL
 *   0x08 ONESHOT      0x09 MAIN         0x0A PRED         0x0B FIELD
 *   0x0C RESULT       0x0D STR_IDX      0x0E CONST_REF    0x0F RESERVED
 *   0x10 OPEN_DICT    0x11 CLOSE_DICT   0x12 OPEN_KEY     0x13 CLOSE_KEY
 *   0x14 OPEN_ARRAY   0x15 CLOSE_ARRAY  0x16 OPEN_TUPLE   0x17 CLOSE_TUPLE
 *
 * FLAGS:
 *   0x40 SURVIVES_RESET (io_call, p_call_composite)
 *   0x80 POINTER        (pt_m_call)
 */

/*
 * Module: dispatch_test
 * Hash:   0xD00FA9D8
 * Trees:  1
 * Records: 1
 * Strings: 19
 * Constants: 0
 * Param size: 8 bytes (32-bit)
 */

// ============================================================================
// STRING TABLE
// ============================================================================
/*
 * [0x0000] (  0) hash=0x16F84D20 "State machine test started "
 * [0x0001] (  1) hash=0xBE1A3917 "event_actions_fn[1]"
 * [0x0002] (  2) hash=0x748EB390 "event_actions_fn[1] terminated"
 * [0x0003] (  3) hash=0xBE20F4DC "event_actions_fn[2]"
 * [0x0004] (  4) hash=0x97AE2D3D "event_actions_fn[2] terminated"
 * [0x0005] (  5) hash=0x821E57D1 "event_actions_fn[3]"
 * [0x0006] (  6) hash=0xCD84EEA6 "event_actions_fn[3] terminated"
 * [0x0007] (  7) hash=0x8226A696 "event_actions_fn[4]"
 * [0x0008] (  8) hash=0xC3158383 "event_actions_fn[4] terminated"
 * [0x0009] (  9) hash=0x686BC2DF "field_actions_fn[1]"
 * [0x000A] ( 10) hash=0xC6861B38 "field_actions_fn[1] terminated"
 * [0x000B] ( 11) hash=0x687411A4 "field_actions_fn[2]"
 * [0x000C] ( 12) hash=0xD2D95985 "field_actions_fn[2] terminated"
 * [0x000D] ( 13) hash=0xAC70AB19 "field_actions_fn[3]"
 * [0x000E] ( 14) hash=0x61EB8EEE "field_actions_fn[3] terminated"
 * [0x000F] ( 15) hash=0x89FA9636 "State 0"
 * [0x0010] ( 16) hash=0x8AFA97C9 "State 1"
 * [0x0011] ( 17) hash=0x87FA9310 "State 2"
 * [0x0012] ( 18) hash=0x8300AF51 "State 2 terminated"
 */

// ============================================================================
// FUNCTION TABLES
// ============================================================================
/*
 * ONESHOT FUNCTIONS (type=0x08, with 0x40=io_call):
 *   [0x0000] ( 0) hash=0xFFF84A15 SE_SET_FIELD
 *   [0x0001] ( 1) hash=0xCEBBEFA4 SE_LOG
 *   [0x0002] ( 2) hash=0x8BA62F1B DISPLAY_EVENT_INFO
 *   [0x0003] ( 3) hash=0xCF729BCE SE_QUEUE_EVENT
 *
 * MAIN FUNCTIONS (type=0x09, with 0x80=pt_m_call):
 *   [0x0000] ( 0) hash=0xC7FEA7F6 SE_FUNCTION_INTERFACE
 *   [0x0001] ( 1) hash=0xF3EDFC75 SE_EVENT_DISPATCH
 *   [0x0002] ( 2) hash=0xFFC1FAA4 SE_CHAIN_FLOW
 *   [0x0003] ( 3) hash=0x8CD80263 SE_RETURN_PIPELINE_RESET
 *   [0x0004] ( 4) hash=0x4AC84487 SE_RETURN_PIPELINE_HALT
 *   [0x0005] ( 5) hash=0xA1C11B35 SE_FIELD_DISPATCH
 *   [0x0006] ( 6) hash=0x0C3460EB SE_TICK_DELAY
 *   [0x0007] ( 7) hash=0x5EEDA8E9 SE_STATE_MACHINE
 *   [0x0008] ( 8) hash=0x0A24332A SE_FORK
 *   [0x0009] ( 9) hash=0xDFE64C74 SE_RETURN_TERMINATE
 *
 */

// ============================================================================
// RECORD DEFINITIONS
// ============================================================================
/*
 * RECORD[0x0000]: state_machine_blackboard (size=20, align=4, hash=0xC89D038C)
 *   [ 0] off=0x0000 size= 4 hash=0x783132F6 state
 *   [ 1] off=0x0004 size= 4 hash=0x0BFA174C event_data_1
 *   [ 2] off=0x0008 size= 4 hash=0x0EFA1C05 event_data_2
 *   [ 3] off=0x000C size= 4 hash=0x0DFA1A72 event_data_3
 *   [ 4] off=0x0010 size= 4 hash=0x08FA1293 event_data_4
 *
 */

// ============================================================================
// TREE PARAMETERS
// ============================================================================
/*
 * TREE: dispatch_test
 *   hash=0xD00FA9D8 nodes=66 ptrs=6
 *   record=state_machine_blackboard (hash=0xC89D038C)
 *
 * IDX   TYPE[CODE]       u16_a  u16_b  VALUE/DETAILS
 * -------------------------------------------------------------------------
 *    0  OPEN_CALL[0x07]    261      0  SE_FUNCTION_INTERFACE hash=0xC7FEA7F6
 *    1  MAIN      [0x09]      0      0  idx_to_ptr=0
 *    2    OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *    3    ONESHOT+SR[0x48]      2      0  idx_to_ptr=0
 *    4      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *    5      UINT[0x01]           -      -  0 (0x00000000)
 *    6    CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *    7    OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *    8    ONESHOT   [0x08]      7      1  idx_to_ptr=0
 *    9      STR_IDX[0x0D]        0     27  "State machine test started "
 *   10    CLOSE[0x06]          0      -  (end SE_LOG)
 *   11    OPEN_CALL[0x07]     91      0  SE_EVENT_DISPATCH hash=0xF3EDFC75
 *   12    MAIN      [0x09]     11      1  idx_to_ptr=0
 *   13      INT[0x00]            -      -  1 (0x00000001)
 *   14      OPEN_CALL[0x07]     21      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   15      MAIN      [0x09]     14      2  idx_to_ptr=0
 *   16        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   17        ONESHOT   [0x08]     16      1  idx_to_ptr=0
 *   18          STR_IDX[0x0D]        1     19  "event_actions_fn[1]"
 *   19        CLOSE[0x06]          0      -  (end SE_LOG)
 *   20        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   21        ONESHOT   [0x08]     20      2  idx_to_ptr=0
 *   22        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   23        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   24        ONESHOT   [0x08]     23      0  idx_to_ptr=0
 *   25          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   26          UINT[0x01]           -      -  1 (0x00000001)
 *   27        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   28        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   29        ONESHOT   [0x08]     28      1  idx_to_ptr=0
 *   30          STR_IDX[0x0D]        2     30  "event_actions_fn[1] terminated"
 *   31        CLOSE[0x06]          0      -  (end SE_LOG)
 *   32        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   33        MAIN      [0x09]     32      3  idx_to_ptr=0
 *   34        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   35      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   36      INT[0x00]            -      -  3 (0x00000003)
 *   37      OPEN_CALL[0x07]     21      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   38      MAIN      [0x09]     37      2  idx_to_ptr=0
 *   39        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   40        ONESHOT   [0x08]     39      1  idx_to_ptr=0
 *   41          STR_IDX[0x0D]        3     19  "event_actions_fn[2]"
 *   42        CLOSE[0x06]          0      -  (end SE_LOG)
 *   43        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   44        ONESHOT   [0x08]     43      2  idx_to_ptr=0
 *   45        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   46        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *   47        ONESHOT   [0x08]     46      0  idx_to_ptr=0
 *   48          FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *   49          UINT[0x01]           -      -  2 (0x00000002)
 *   50        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *   51        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   52        ONESHOT   [0x08]     51      1  idx_to_ptr=0
 *   53          STR_IDX[0x0D]        4     30  "event_actions_fn[2] terminated"
 *   54        CLOSE[0x06]          0      -  (end SE_LOG)
 *   55        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   56        MAIN      [0x09]     55      3  idx_to_ptr=0
 *   57        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   58      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   59      INT[0x00]            -      -  2 (0x00000002)
 *   60      OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   61      MAIN      [0x09]     60      2  idx_to_ptr=0
 *   62        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   63        ONESHOT   [0x08]     62      1  idx_to_ptr=0
 *   64          STR_IDX[0x0D]        5     19  "event_actions_fn[3]"
 *   65        CLOSE[0x06]          0      -  (end SE_LOG)
 *   66        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   67        ONESHOT   [0x08]     66      2  idx_to_ptr=0
 *   68        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   69        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   70        ONESHOT   [0x08]     69      1  idx_to_ptr=0
 *   71          STR_IDX[0x0D]        6     30  "event_actions_fn[3] terminated"
 *   72        CLOSE[0x06]          0      -  (end SE_LOG)
 *   73        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   74        MAIN      [0x09]     73      3  idx_to_ptr=0
 *   75        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   76      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   77      INT[0x00]            -      -  4 (0x00000004)
 *   78      OPEN_CALL[0x07]     16      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   79      MAIN      [0x09]     78      2  idx_to_ptr=0
 *   80        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   81        ONESHOT   [0x08]     80      1  idx_to_ptr=0
 *   82          STR_IDX[0x0D]        7     19  "event_actions_fn[4]"
 *   83        CLOSE[0x06]          0      -  (end SE_LOG)
 *   84        OPEN_CALL[0x07]      2      0  DISPLAY_EVENT_INFO hash=0x8BA62F1B
 *   85        ONESHOT   [0x08]     84      2  idx_to_ptr=0
 *   86        CLOSE[0x06]          0      -  (end DISPLAY_EVENT_INFO)
 *   87        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *   88        ONESHOT   [0x08]     87      1  idx_to_ptr=0
 *   89          STR_IDX[0x0D]        8     30  "event_actions_fn[4] terminated"
 *   90        CLOSE[0x06]          0      -  (end SE_LOG)
 *   91        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *   92        MAIN      [0x09]     91      3  idx_to_ptr=0
 *   93        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *   94      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *   95      INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *   96      OPEN_CALL[0x07]      5      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *   97      MAIN      [0x09]     96      2  idx_to_ptr=0
 *   98        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_HALT hash=0x4AC84487
 *   99        MAIN      [0x09]     98      4  idx_to_ptr=0
 *  100        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_HALT)
 *  101      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  102    CLOSE[0x06]          0      -  (end SE_EVENT_DISPATCH)
 *  103    OPEN_CALL[0x07]     60      0  SE_FIELD_DISPATCH hash=0xA1C11B35
 *  104    MAIN      [0x09]    103      5  idx_to_ptr=0
 *  105      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *  106      INT[0x00]            -      -  1 (0x00000001)
 *  107      OPEN_CALL[0x07]     17      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  108      MAIN      [0x09]    107      2  idx_to_ptr=0
 *  109        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  110        ONESHOT   [0x08]    109      1  idx_to_ptr=0
 *  111          STR_IDX[0x0D]        9     19  "field_actions_fn[1]"
 *  112        CLOSE[0x06]          0      -  (end SE_LOG)
 *  113        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  114        MAIN+PTR  [0x89]    113      6  idx_to_ptr=0
 *  115          INT[0x00]            -      -  5 (0x00000005)
 *  116        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  117        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  118        ONESHOT   [0x08]    117      1  idx_to_ptr=0
 *  119          STR_IDX[0x0D]       10     30  "field_actions_fn[1] terminated"
 *  120        CLOSE[0x06]          0      -  (end SE_LOG)
 *  121        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  122        MAIN      [0x09]    121      3  idx_to_ptr=0
 *  123        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  124      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  125      INT[0x00]            -      -  2 (0x00000002)
 *  126      OPEN_CALL[0x07]     17      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  127      MAIN      [0x09]    126      2  idx_to_ptr=0
 *  128        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  129        ONESHOT   [0x08]    128      1  idx_to_ptr=0
 *  130          STR_IDX[0x0D]       11     19  "field_actions_fn[2]"
 *  131        CLOSE[0x06]          0      -  (end SE_LOG)
 *  132        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  133        MAIN+PTR  [0x89]    132      6  idx_to_ptr=1
 *  134          INT[0x00]            -      -  5 (0x00000005)
 *  135        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  136        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  137        ONESHOT   [0x08]    136      1  idx_to_ptr=0
 *  138          STR_IDX[0x0D]       12     30  "field_actions_fn[2] terminated"
 *  139        CLOSE[0x06]          0      -  (end SE_LOG)
 *  140        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  141        MAIN      [0x09]    140      3  idx_to_ptr=0
 *  142        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  143      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  144      INT[0x00]            -      -  -1 (0xFFFFFFFF)
 *  145      OPEN_CALL[0x07]     17      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  146      MAIN      [0x09]    145      2  idx_to_ptr=0
 *  147        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  148        ONESHOT   [0x08]    147      1  idx_to_ptr=0
 *  149          STR_IDX[0x0D]       13     19  "field_actions_fn[3]"
 *  150        CLOSE[0x06]          0      -  (end SE_LOG)
 *  151        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  152        MAIN+PTR  [0x89]    151      6  idx_to_ptr=2
 *  153          INT[0x00]            -      -  5 (0x00000005)
 *  154        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  155        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  156        ONESHOT   [0x08]    155      1  idx_to_ptr=0
 *  157          STR_IDX[0x0D]       14     30  "field_actions_fn[3] terminated"
 *  158        CLOSE[0x06]          0      -  (end SE_LOG)
 *  159        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  160        MAIN      [0x09]    159      3  idx_to_ptr=0
 *  161        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  162      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  163    CLOSE[0x06]          0      -  (end SE_FIELD_DISPATCH)
 *  164    OPEN_CALL[0x07]     96      0  SE_STATE_MACHINE hash=0x5EEDA8E9
 *  165    MAIN      [0x09]    164      7  idx_to_ptr=0
 *  166      FIELD[0x0B]          0      4  state (off=0x0000, hash=0x783132F6)
 *  167      INT[0x00]            -      -  0 (0x00000000)
 *  168      OPEN_CALL[0x07]     35      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  169      MAIN      [0x09]    168      2  idx_to_ptr=0
 *  170        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  171        ONESHOT   [0x08]    170      1  idx_to_ptr=0
 *  172          STR_IDX[0x0D]       15      7  "State 0"
 *  173        CLOSE[0x06]          0      -  (end SE_LOG)
 *  174        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  175        MAIN+PTR  [0x89]    174      6  idx_to_ptr=3
 *  176          INT[0x00]            -      -  20 (0x00000014)
 *  177        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  178        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  179        ONESHOT   [0x08]    178      0  idx_to_ptr=0
 *  180          FIELD[0x0B]          4      4  event_data_1 (off=0x0004, hash=0x0BFA174C)
 *  181          FLOAT[0x02]          -      -  1.1
 *  182        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  183        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  184        ONESHOT   [0x08]    183      0  idx_to_ptr=0
 *  185          FIELD[0x0B]          8      4  event_data_2 (off=0x0008, hash=0x0EFA1C05)
 *  186          FLOAT[0x02]          -      -  2.2
 *  187        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  188        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  189        ONESHOT   [0x08]    188      3  idx_to_ptr=0
 *  190          UINT[0x01]           -      -  1 (0x00000001)
 *  191          UINT[0x01]           -      -  1 (0x00000001)
 *  192          FIELD[0x0B]          4      4  event_data_1 (off=0x0004, hash=0x0BFA174C)
 *  193        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  194        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  195        ONESHOT   [0x08]    194      3  idx_to_ptr=0
 *  196          UINT[0x01]           -      -  1 (0x00000001)
 *  197          UINT[0x01]           -      -  2 (0x00000002)
 *  198          FIELD[0x0B]          8      4  event_data_2 (off=0x0008, hash=0x0EFA1C05)
 *  199        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  200        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  201        MAIN      [0x09]    200      3  idx_to_ptr=0
 *  202        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  203      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  204      INT[0x00]            -      -  1 (0x00000001)
 *  205      OPEN_CALL[0x07]     35      0  SE_CHAIN_FLOW hash=0xFFC1FAA4
 *  206      MAIN      [0x09]    205      2  idx_to_ptr=0
 *  207        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  208        ONESHOT   [0x08]    207      1  idx_to_ptr=0
 *  209          STR_IDX[0x0D]       16      7  "State 1"
 *  210        CLOSE[0x06]          0      -  (end SE_LOG)
 *  211        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  212        MAIN+PTR  [0x89]    211      6  idx_to_ptr=4
 *  213          INT[0x00]            -      -  20 (0x00000014)
 *  214        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  215        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  216        ONESHOT   [0x08]    215      0  idx_to_ptr=0
 *  217          FIELD[0x0B]         12      4  event_data_3 (off=0x000C, hash=0x0DFA1A72)
 *  218          FLOAT[0x02]          -      -  3.3
 *  219        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  220        OPEN_CALL[0x07]      4      0  SE_SET_FIELD hash=0xFFF84A15
 *  221        ONESHOT   [0x08]    220      0  idx_to_ptr=0
 *  222          FIELD[0x0B]         16      4  event_data_4 (off=0x0010, hash=0x08FA1293)
 *  223          FLOAT[0x02]          -      -  4.4
 *  224        CLOSE[0x06]          0      -  (end SE_SET_FIELD)
 *  225        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  226        ONESHOT   [0x08]    225      3  idx_to_ptr=0
 *  227          UINT[0x01]           -      -  1 (0x00000001)
 *  228          UINT[0x01]           -      -  3 (0x00000003)
 *  229          FIELD[0x0B]         12      4  event_data_3 (off=0x000C, hash=0x0DFA1A72)
 *  230        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  231        OPEN_CALL[0x07]      5      0  SE_QUEUE_EVENT hash=0xCF729BCE
 *  232        ONESHOT   [0x08]    231      3  idx_to_ptr=0
 *  233          UINT[0x01]           -      -  1 (0x00000001)
 *  234          UINT[0x01]           -      -  4 (0x00000004)
 *  235          FIELD[0x0B]         16      4  event_data_4 (off=0x0010, hash=0x08FA1293)
 *  236        CLOSE[0x06]          0      -  (end SE_QUEUE_EVENT)
 *  237        OPEN_CALL[0x07]      2      0  SE_RETURN_PIPELINE_RESET hash=0x8CD80263
 *  238        MAIN      [0x09]    237      3  idx_to_ptr=0
 *  239        CLOSE[0x06]          0      -  (end SE_RETURN_PIPELINE_RESET)
 *  240      CLOSE[0x06]          0      -  (end SE_CHAIN_FLOW)
 *  241      INT[0x00]            -      -  2 (0x00000002)
 *  242      OPEN_CALL[0x07]     17      0  SE_FORK hash=0x0A24332A
 *  243      MAIN      [0x09]    242      8  idx_to_ptr=0
 *  244        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  245        ONESHOT   [0x08]    244      1  idx_to_ptr=0
 *  246          STR_IDX[0x0D]       17      7  "State 2"
 *  247        CLOSE[0x06]          0      -  (end SE_LOG)
 *  248        OPEN_CALL[0x07]      3      0  SE_TICK_DELAY hash=0x0C3460EB
 *  249        MAIN+PTR  [0x89]    248      6  idx_to_ptr=5
 *  250          INT[0x00]            -      -  20 (0x00000014)
 *  251        CLOSE[0x06]          0      -  (end SE_TICK_DELAY)
 *  252        OPEN_CALL[0x07]      3      0  SE_LOG hash=0xCEBBEFA4
 *  253        ONESHOT   [0x08]    252      1  idx_to_ptr=0
 *  254          STR_IDX[0x0D]       18     18  "State 2 terminated"
 *  255        CLOSE[0x06]          0      -  (end SE_LOG)
 *  256        OPEN_CALL[0x07]      2      0  SE_RETURN_TERMINATE hash=0xDFE64C74
 *  257        MAIN      [0x09]    256      9  idx_to_ptr=0
 *  258        CLOSE[0x06]          0      -  (end SE_RETURN_TERMINATE)
 *  259      CLOSE[0x06]          0      -  (end SE_FORK)
 *  260    CLOSE[0x06]          0      -  (end SE_STATE_MACHINE)
 *  261  CLOSE[0x06]          0      -  (end SE_FUNCTION_INTERFACE)
 *
 * Total params: 262
 */

#endif // DISPATCH_TEST_DUMP_32_H
