// ============================================================================
// dispatch_test.h
// Generated S-expression module for dispatch_test
// DO NOT EDIT - Generated by s_expr_dsl v5.3
// ============================================================================

#ifndef DISPATCH_TEST_H
#define DISPATCH_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "dispatch_test_records.h"

// Module: dispatch_test
#define DISPATCH_TEST_NAME_HASH 0xD00FA9D8
#define DISPATCH_TEST_TREE_COUNT 1
#define DISPATCH_TEST_RECORD_COUNT 1

// String table
static const char* const dispatch_test_strings[] = {
    "State machine test started ",
    "event_actions_fn[1]",
    "event_actions_fn[1] terminated",
    "event_actions_fn[2]",
    "event_actions_fn[2] terminated",
    "event_actions_fn[3]",
    "event_actions_fn[3] terminated",
    "event_actions_fn[4]",
    "event_actions_fn[4] terminated",
    "field_actions_fn[1]",
    "field_actions_fn[1] terminated",
    "field_actions_fn[2]",
    "field_actions_fn[2] terminated",
    "field_actions_fn[3]",
    "field_actions_fn[3] terminated",
    "State 0",
    "State 1",
    "State 2",
    "State 2 terminated"
};
#define DISPATCH_TEST_STRING_COUNT 19

// Function hashes
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_HASH 0xCEBBEFA4
#define DISPLAY_EVENT_INFO_HASH 0x8BA62F1B
#define SE_QUEUE_EVENT_HASH 0xCF729BCE
#define SE_FUNCTION_INTERFACE_HASH 0xC7FEA7F6
#define SE_EVENT_DISPATCH_HASH 0xF3EDFC75
#define SE_CHAIN_FLOW_HASH 0xFFC1FAA4
#define SE_RETURN_PIPELINE_RESET_HASH 0x8CD80263
#define SE_RETURN_PIPELINE_HALT_HASH 0x4AC84487
#define SE_FIELD_DISPATCH_HASH 0xA1C11B35
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_STATE_MACHINE_HASH 0x5EEDA8E9
#define SE_FORK_HASH 0x0A24332A
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74

// Tree hashes
#define DISPATCH_TEST_HASH 0xD00FA9D8

// Record hashes
#define STATE_MACHINE_BLACKBOARD_HASH 0xC89D038C

// Field hashes
#define FIELD_STATE_HASH 0x783132F6
#define FIELD_EVENT_DATA_1_HASH 0x0BFA174C
#define FIELD_EVENT_DATA_2_HASH 0x0EFA1C05
#define FIELD_EVENT_DATA_3_HASH 0x0DFA1A72
#define FIELD_EVENT_DATA_4_HASH 0x08FA1293

#ifdef __cplusplus
}
#endif

#endif // DISPATCH_TEST_H
